<div style="text-align: center;">

  <!-- Logotipo -->
  <img src="img/LogoUesc.png" alt="UESC" style="width: 60px; display: block; margin: 0 auto 5px auto;">

  <!-- Cabeçalho -->
  <div style="font-size: 20px;"><strong>UNIVERSIDADE ESTADUAL DE SANTA CRUZ - UESC</strong></div>
  <div style="font-size: 18px;">DEPARTAMENTO DE ENGENHARIAS E COMPUTAÇÃO</div>
  <div style="font-size: 18px;">ENGENHARIA QUÍMICA</div>

  <hr style="margin: 20px 0; border: 1px solid #0074B7;">

  <!-- Título do Trabalho -->
  <div style="font-size: 22px; font-weight: bold; margin-bottom: 10px;">Modelagem, Simulação e Otimização de Processos Químicos</div>
  <div style="font-size: 20px; font-weight: bold; margin-bottom: 10px;"> Resolução de Transferência de Calor em Placas - Matrizes 4x4</div>

  <!-- Autor e orientador -->
  <div style="font-size: 18px;">Prof. Dr. E.R.Edwards</div>

<hr style="margin: 20px 0; border: 1px solid #0074B7;">
  <!-- Data -->
<!-- <div style="font-size: 16px; margin-top: 15px;">Ilhéus - BA, Abril de 2025</div> -->
</div>

**Exercício**
Considere uma placa retangular com alguma fonte de calor em cada borda. Para determinar o equilíbrio na placa, podemos assumir que se ela estiver em equilíbrio a temperatura será dada pela média das temperaturas dos quatro pontos da grade mais próxima de $T_{ij}$. Isso cria um sistema linear para $T_{ij}$, que pode ser resolvida aplicando métodos de resolução matricial. Para uma grade quadrada a resolução é feita pela **Equação de Diferenças de Laplace** aplicando a expressão abaixo:

$$ T_{ij}=\frac{T_{i+1,j} + T_{i-1,j} + T_{i,j+1}  + T_{i,j-1}}{4}  ...Eq(1)$$

<img src="img/Placa.png" alt="UESC" style="width: 600px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;">Fonte<strong>: Desenho esquemático de um processo de produção de metanol</strong></p>

#### Resolução:

Vamos chamar $T_{11}=x_1$, $T_{12}=x_2$, $T_{21}=x_3$ e $T_{22}=x_4$. Então aplicando a Eq(1), teremos:

No ponto $T_{11}$:
$$  x_1 = \frac{20 + 50 + x_2 + x_3}{4} $$

No ponto $T_{12}$:
$$  x_2 = \frac{20 + 50 + x_1 + x_4}{4} $$

No ponto $T_{21}$:
$$  x_3 = \frac{20 + 20 + x_1 + x_4}{4} $$

No ponto $T_{22}$:
$$  x_4 = \frac{20 + 20 + x_2 + x_3  }{4} $$

#### Vamos rearranjar as equações

$$ 4x_1 - x_2 - x_3  - 0 x_4 = 70 $$
$$- x_1 + 4x_2 - 0 x_3 - x_4 = 70 $$
$$- x_1 - 0 x_2 + 4x_3  - x_4 = 40 $$
$$0 x_1 - x_2 - x_3 + 4x_4  = 40 $$

Observe que temos 4 equações e 4 incógnitas formando uma matriz $4x4$ que pode ser resolvida por $A.x=b$ sendo:

\begin{equation}
	\begin{bmatrix}
		4 & -1  & -1 & 0 \\
		-1 & 4  & 0 & -1 \\
		-1 & 4  & 0 & -1 \\
		0 & -1  & -1 & 4 \nonumber \\ 
	\end{bmatrix} 
    .
    \begin{bmatrix}
		x_1 \\
		x_2 \\
		x_3 \\
		x_4 \nonumber \\ 
	\end{bmatrix}
    =
    \begin{bmatrix}
		70 \\
		70 \\
		40 \\
		40 \nonumber \\ 
	\end{bmatrix}
\end{equation}

Temos que determinar as temperaturas nos pontos $x_1$, $x_2$, $x_3$, $x_4$.

#### Preparando os dados para os cálculos.

\begin{equation}
	A = 
	\begin{bmatrix}
		a_{11} & a_{12}  & a_{13} & a_{14} \\
		a_{21} & a_{22}  & a_{23} & a_{24} \\
		a_{31} & a_{32}  & a_{33} & a_{34} \\
		a_{41} & a_{42}  & a_{43} & a_{44} \nonumber \\ 
	\end{bmatrix} 
    =
    \begin{bmatrix}
		4 & -1  & -1 & 0 \\
		-1 & 4  & 0 & -1 \\
		-1 & 0  & 4 & -1 \\
		0 & -1  & -1 & 4 \nonumber \\ 
	\end{bmatrix}
\end{equation}

**Passos para os cálculos**

1 - Calcular a matriz cofator: $A_c = (-1)^{(i+j)} [a_{ij}]$  

2 - Calcular a matriz Transposta $A^T$.

3 - Cálcular o Determinante da matriz - D

4 - Calcular a matriz inversa $A^{-1}$:$A^{-1} = \frac{1}{det(A)}.A^T $

5 - Calcular as incógnitas $x$ na expressão: $x = \frac{b}{A} = A^{-1}b$ 


#### Cálculos

In [115]:
# Matriz A
a11, a12, a13, a14 = 4, -1, -1, 0
a21, a22, a23, a24 = -1, 4, 0, -1
a31, a32, a33, a34 = -1, 0, 4, -1
a41, a42, a43, a44 = 0, -1, -1, 4

1 - Calculo da matriz cofator: $A_c = (-1)^{(i+j)} [a_{ij}]$ 

In [116]:
# Cálculo para a11
# Indices de linhas e colunas a11
i = 1
j = 1
matriz11 = a22*((a33*a44)-(a34*a43))-a23*((a32*a44)-(a34*a42))+a24*((a32*a43)-(a33*a42))

c11 = (-1)**(i+j)*matriz11
matriz11

56

In [117]:
# Cálculo para a12
# Indices de linhas e colunas a12
i = 1
j = 2
matriz12 = a21*((a33*a44)-(a34*a43))-a23*((a31*a44)-(a34*a41))+a24*((a31*a43)-(a33*a41))
c12 = (-1)**(i+j)*matriz12
c12

16

In [118]:
# Cálculo para a13
# Indices de linhas e colunas a13
i = 1
j = 3
matriz13 = a21*((a32*a44)-(a42*a34))-a31*((a22*a44)-(a42*a24))+a41*((a22*a34)-(a32*a24))
c13 = (-1)**(i+j)*matriz13
c13

16

In [119]:
# Cálculo para a14
# Indices de linhas e colunas a14.
i = 1
j = 4

matriz14 = a21*((a32*a43)-(a33*a42))-a22*((a31*a43)-(a33*a41))+a23*((a31*a42)-(a32*a41))
c14 = (-1)**(i+j)*matriz14
c14

8

In [120]:
# Cálculo para a21.
# Indices de linhas e colunas a21
i = 2
j = 1

matriz21 = a12*((a33*a44)-(a34*a43))-a13*((a32*a44)-(a34*a42))+a14*((a32*a43)-(a33*a42))
c21 = (-1)**(i+j)*matriz21
c21

16

In [121]:
# Cálculo para a22
# Indices de linhas e colunas a22
i = 2
j = 2

matriz22 = a11*((a33*a44)-(a34*a43))-a13*((a31*a44)-(a34*a41))+a14*((a31*a43)-(a33*a41))
c22 = (-1)**(i+j)*matriz22
c22

56

In [122]:
# Cálculo para a23.
# Indices de linhas e colunas a23.
i = 2
j = 3

matriz23 = a11*((a32*a44)-(a34*a42))-a12*((a31*a44)-(a34*a41))+ a14*((a31*a42)-(a32*a41))
c23 = (-1)**(i+j)*matriz23
c23

8

In [123]:
# Cálculo para a24
# Indices de linhas e colunas a24
i = 2
j = 4

matriz24 = a11*((a32*a43)-(a33*a42))-a12*((a31*a43)-(a33*a41))+a13*((a31*a42)-(a32*a41))
c24 = (-1)**(i+j)*matriz24
c24

16

In [124]:
# Cálculo para a31
# Indices de linhas e colunas a31
i = 3
j = 1

matriz31 = a12*((a23*a44)-(a24*a43))-a13*((a22*a44)-(a24*a42))+a14*((a22*a43)-(a23*a42))
c31 = (-1)**(i+j)*matriz31
c31

16

In [125]:
# Cálculo para a32
# Indices de linhas e colunas a32
i = 3
j = 2

matriz32 = a11*((a23*a44)-(a24*a43))-a13*((a21*a44)-(a24*a41))+a14*((a21*a43)-(a23*a41))
c32 = (-1)**(i+j)*matriz32
c32

8

In [126]:
# Cálculo para a33
# indice de linhas e colunas a33.
i = 3
j = 3

matriz33 = a11*((a22*a44)-(a24*a42))-a12*((a21*a44)-(a24*a41))+a14*((a21*a42)-(a22*a41))
c33 = (-1)**(i+j)*matriz33
c33

56

In [127]:
# Cálculo para a34
# Indice de linhas e colunas a34.
i = 3
j = 4

matriz34 = a11*((a22*a43)-(a23*a42))-a12*((a21*a43)-(a23*a41))+a13*((a21*a42)-(a22*a41))
c34 = (-1)**(i+j)*matriz34
c34

16

In [128]:
# Cálculo para a41
# Indice de linhas e colunas a41
i = 4
j = 1

matriz41 = a12*((a23*a34)-(a24*a33))-a13*((a22*a34)-(a24*a32))+a14*((a22*a33)-(a23*a32))
c41 = (-1)**(i+j)*matriz41
c41

8

In [129]:
# Cálculo para a41
# Indice de linhas e colunas a42
i = 4
j = 2

matriz42 = a11*((a23*a34)-(a24*a33))-a13*((a21*a34)-(a24*a31))+a14*((a21*a33)-(a23*a31))
c42 = (-1)**(i+j)*matriz42
c42

16

In [130]:
# Cálculo para a43
# Indice de linhas e colunas a43
i = 4
j = 3

matriz43 = a11*((a22*a34)-(a24*a32))-a12*((a21*a34)-(a24*a31))+a14*((a21*a32)-(a22*a31))
c43 = (-1)**(i+j)*matriz43
c43

16

In [131]:
# Cálculo para a44
# Indice de linhas e colunas a44.
i = 4
j = 4

matriz44 = a11*((a22*a33)-(a23*a32))-a12*((a21*a33)-(a23*a31))+a13*((a21*a32)-(a22*a31))
c44 = (-1)**(i+j)*matriz44
c44

56

Agora vamos substituir os valores encontrados para cada cofator $c_{ij}$ na matriz $A$ para forma a matriz cofator $A_c$.

In [132]:
import numpy as np

Ac = np.array([[c11, c12, c13, c14],
               [c21, c22, c23, c24],
               [c31, c23, c33, c34],
               [c41, c42, c43, c44]

])
Ac

array([[56, 16, 16,  8],
       [16, 56,  8, 16],
       [16,  8, 56, 16],
       [ 8, 16, 16, 56]])

#### Cálculo da  Matriz transposta ($A^T$).

Nós podemos cálcular a matriz transposta fazendo a linha da matriz se transforma em coluna conforme abaixo.

In [133]:
Matriz_T = [[c11, c21, c31, c41],
            [c12, c22, c32, c42],
            [c13, c23, c33, c43],
            [c14, c24, c34, c44]]
Matriz_T

[[56, 16, 16, 8], [16, 56, 8, 16], [16, 8, 56, 16], [8, 16, 16, 56]]

Nós também podemos usar a biblioteca Numpy e resolver a transposta de uma matriz conforme mostrado abaixo.

In [134]:
AT = np.transpose(Ac)
AT

array([[56, 16, 16,  8],
       [16, 56,  8, 16],
       [16,  8, 56, 16],
       [ 8, 16, 16, 56]])

Nós já temos a matriz Transposta $A^T$, agora precisamos calcular o Determinante de uma matriz $4x4$ e subistituir os resultados na Eq(2).

Vamos repetir a matriz $A$ com os valores numéricos abaixo:

\begin{equation}
	A = 
	\begin{bmatrix}
		a_{11} & a_{12}  & a_{13} & a_{14} \\
		a_{21} & a_{22}  & a_{23} & a_{24} \\
		a_{31} & a_{32}  & a_{33} & a_{34} \\
		a_{41} & a_{42}  & a_{43} & a_{44} \nonumber \\ 
	\end{bmatrix} 
    =
    \begin{bmatrix}
		4 & -1  & -1 & 0 \\
		-1 & 4  & 0 & -1 \\
		-1 & 0  & 4 & -1 \\
		0 & -1  & -1 & 4 \nonumber \\ 
	\end{bmatrix}
\end{equation}

O Determinante será encontrado fazendo:

$$ D = \sum a_{ij}A_{ij} $$

Ele poderá ser encontrado a partir de uma linha ou coluna. Vamos escolher a que apresenta muitos zeros porque qualquer número multiplicado por zero é igual a zero. Dessa forma o cálculo ficará mais fácil. Então vamos escolher a primeira linha para fazer o cálculo do Determinante.

$$
 D = a_{11}A_{11} + a_{12}A_{12} + a_{13}A_{13} + a_{14}A_{14}
  $$

$$ 
D = 4A_{11} -1A_{12} -1A_{13} + 0A_{14} 
$$

Vamos usar a Eq(5) para calcular as matrizes $A_{ij}$ (repetido abaixo)

$$
 A_c = (-1)^{(i+j)} [a_{ij}] ... Eq(5)
 $$ 

Já foi calculado acima: $A_{11}=c_{11}$, $A_{12}=c_{12}$ e $A_{13}=c_{13}$.


In [135]:
D = 4*c11 -1*c12 -1*c13 + 0*c14
D

192

Substituindo os valores na Equação (1) para determinar a matriz inversa, ($A^{-1}$), temos:

In [136]:
A_inv = (1/D)*AT
A_inv

array([[0.29166667, 0.08333333, 0.08333333, 0.04166667],
       [0.08333333, 0.29166667, 0.04166667, 0.08333333],
       [0.08333333, 0.04166667, 0.29166667, 0.08333333],
       [0.04166667, 0.08333333, 0.08333333, 0.29166667]])

#### Cálculo das incógnitas $x$.

In [137]:
import numpy as np

In [138]:
b = np.array([70, 70, 40, 40])
b

array([70, 70, 40, 40])

In [139]:
# Cálculo de x=A^-1.b usando método algébrico.
# Extraindo os valores de b
b1=b[0]
b2=b[1]
b3=b[2]
b4=b[3]

In [140]:
# Cálculo de x.

x1 = A_inv[0][0]*b1 + A_inv[0][1]*b2 + A_inv[0][2]*b3 + A_inv[0][3]*b4
T11 = print('O valor de T11 = {:.2f}'.format(x1), 'C') 

x2 = A_inv[1][0]*b1 + A_inv[1][1]*b2 + A_inv[1][2]*b3 + A_inv[1][3]*b4
T12 = print('O valor de T12 = {:.2f}'.format(x2), 'C') 

x3 = A_inv[2][0]*b1 + A_inv[2][1]*b2 + A_inv[2][2]*b3 + A_inv[2][3]*b4
T13 = print('O valor de T13 = {:.2f}'.format(x3), 'C')

x4 = A_inv[3][0]*b1 + A_inv[3][1]*b2 + A_inv[3][2]*b3 + A_inv[3][3]*b4
T14 = print('O valor de T14 = {:.2f}'.format(x4), 'C')

O valor de T11 = 31.25 C
O valor de T12 = 31.25 C
O valor de T13 = 23.75 C
O valor de T14 = 23.75 C


#### Agora vamos fazer o mesmo cálculo usando a biblioteca Numpy.

Dentro da biblioteca Numpy possui a **Algebra Linear** (*linalg*) que possui todos esses códigos, o que possibilita a resolução com poucas linhas de código.

In [141]:
import numpy as np
import numpy.linalg as nl

# Vamos criar a matriz A
A = np.array([[4, -1, -1, 0],
              [-1, 4, 0, -1],
              [-1, 0, 4, -1],
              [0, -1, -1, 4]
              ])

inversa_A = np.linalg.inv(A)

# Vamos criar a matriz do lado direito - b
b = np.array([70, 70, 40, 40])

# Agora vamos resolver o sistema linear usando np.solve()
x = nl.solve(A, b)
# Também poderiamos ter usado o código abaixo.
# x = np.dot(A_inv, b) 

# Extraindo os valores de x da lista:
T_11 = x[0]
T_12 = x[1]
T_13 = x[2]
T_14 = x[3]

inversa_A

array([[0.29166667, 0.08333333, 0.08333333, 0.04166667],
       [0.08333333, 0.29166667, 0.04166667, 0.08333333],
       [0.08333333, 0.04166667, 0.29166667, 0.08333333],
       [0.04166667, 0.08333333, 0.08333333, 0.29166667]])

In [142]:
print('O valor de T11 = ', T_11, 'C')
print('O valor de T12 = ', T_12, 'C')
print('O valor de T13 = ', T_13, 'C')
print('O valor de T14 = ', T_14, 'C')

O valor de T11 =  31.25 C
O valor de T12 =  31.25 C
O valor de T13 =  23.75 C
O valor de T14 =  23.75 C


<div style="text-align: center; font-size: 12px; color: gray; margin-top: 40px;">
  Este notebook foi desenvolvido no âmbito do Grupo de Pesquisas em Modelagem Computacional da UESC.<br>
  Todos os direitos reservados © 2025
</div>