<div style="text-align: center;">

  <!-- Logotipo -->
  <img src="img/LogoUesc.png" alt="UESC" style="width: 60px; display: block; margin: 0 auto 5px auto;">

  <!-- Cabeçalho -->
  <div style="font-size: 20px;"><strong>UNIVERSIDADE ESTADUAL DE SANTA CRUZ - UESC</strong></div>
  <div style="font-size: 18px;">DEPARTAMENTO DE ENGENHARIAS E COMPUTAÇÃO</div>
  <div style="font-size: 18px;">ENGENHARIA QUÍMICA</div>

  <hr style="margin: 20px 0; border: 1px solid #0074B7;">

  <!-- Título do Trabalho -->
  <div style="font-size: 22px; font-weight: bold; margin-bottom: 10px;">Modelagem, Simulação e Otimização de Processos Químicos</div>
  <div style="font-size: 20px; font-weight: bold; margin-bottom: 10px;">Balanço em Reatores Químicos utilizando Cálculos Matriciais.</div>

  <!-- Autor e orientador -->
  <div style="font-size: 18px;">Prof. Dr. E.R.Edwards</div>

<hr style="margin: 20px 0; border: 1px solid #0074B7;">
  <!-- Data -->
<!-- <div style="font-size: 16px; margin-top: 15px;">Ilhéus - BA, Abril de 2025</div> -->
</div>

__Fonte__:

Sistema de Reatores (Engenharia Química/Bioengenharia)

Steven C. Chapra e Raymond P. Canale, "Métodos Numéricos para Engenharia", $7^a$ Edição. Editora: MacGraw Hill. página 283.



__Fundamentação__.

A conservação de massa é uma das principais organizações na Engenharia Química. Ela contabiliza o balanço de massa que entra em um volume de controle pelo balanço de massa que sai do volume de controle. Caso haja reações químicas esses dados deverão ser contabilizados como acumulo no reator.

$$Acumulo = Entrada - saída$$

Sendo assim, o balanço de massa representa um exercício de contabilidade para a substância específica que esta sendo
modelada. Pelo próprio balanço, se as entradas forem maiores do que as saídas a massa da substância dentro do volume de
controle cresce. Se as saídas forem iguais as entradas o acumulo é igual a zero e a massa permanece constante.

Para condições estáveis ou estacionárias o acumulo será nulo e a equação torna-se.

$$entrada=saída$$

<img src="img/acumulacao.png" alt="UESC" style="width: 500px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Balanço de entradas e saídas em um processo.</strong></p>

Podemos usar a conservação da massa para determinar as concentrações estacionárias de um sistema de reatores.

__Aplicação__:

Vamos analisar o reator abaixo e fazermos um balançco de massa no processo.

Exercício<br>

Calcule a concentração $c_3$ na saída do reator sendo dadas as informações da tabela ao lado.

<img src="img/reator1.png" alt="UESC" style="width: 650px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Desenho esquemático de entradas e saídas em um reator.</strong></p>


$$Q_1.c_1 + Q_2.c_2 =  Q_3.c_3$$

$$ c_3 = \frac{Q_1.c_1 + Q_2.c_2}{Q_3}$$

__Cálculo em Python__

In [1]:
# dados das vazões.
Q1 = 2.0 # m3/min
Q2 = 1.5 # m3/min
Q3 = 3.5 # m3/min

# Dados das concentrações.
c1 = 25 # mg/m3
c2 = 10 # mg/m3

# Cálculo da concentração de saída c3.
c3 = (Q1*c1 + Q2*c2) / Q3

def line():
    print
# Resultado da concentração 3.
print('O resultado da concentração c3 = {:.2f}'.format(c3), 'mg/m3')

O resultado da concentração c3 = 18.57 mg/m3


__Aplicação dos conceitos__ 

__Resolução Matricial do Balanço de Massa em Tanque de Formulação__.

Nesta aplicação, utilizamos métodos matriciais para resolver um problema clássico da Engenharia Química: a mistura de componentes em um tanque de formulação. O sistema analisado consiste em um tanque que recebe três correntes de entrada com composições previamente conhecidas. A corrente de saída apresenta uma vazão total de 1000 kg/h e é composta por 31,0% da substância A, 33,0% da substância B e 36,0% da substância C, conforme ilustrado na figura a seguir. A partir dos dados apresentados qual os fluxos de entrada em cada corrente: $F_1$, $F_2$ e $F_3$. Confira os resultados.

<img src="img/Tanque_3_entradas_1_saida.png" alt="UESC" style="width: 400px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Tanque com três entradas e uma saída.</strong></p>

Vamos encontrar as equações que representam o modelo acima:

\begin{equation}
\begin{aligned}
0.19F_1 + 0.25F_2 + 0.65F_3 &= 0.31*1000 \quad \text{(substância A)} \\
0.52F_1 + 0.35F_2 + 0.11F_3 &= 0.33*1000 \quad \text{(substância B)} \\
0.29F_1 + 0.40F_2 + 0.24F_3 &= 0.36*1000 \quad \text{(substância C)}
\end{aligned}
\end{equation}

Agora vamos transformar essas equações em uma matrix $A.x=b$

\begin{equation}
\begin{bmatrix}
0.19 & 0.25 & 0.65 \\
0.52 & 0.35 & 0.11 \\
0.29 & 0.40 & 0.24 
\end{bmatrix}
.
\begin{bmatrix}
F_1 \\
F_2  \\
F_3
\end{bmatrix}
=
\begin{bmatrix}
310 \\
330 \\
360
\end{bmatrix}
\end{equation}

Cálculo utilizando Programação em Python.

In [2]:
import numpy as np

In [3]:
# Declarando as variáveis.
x11, x12, x13 = 0.19, 0.25, 0.65
x21, x22, x23 = 0.52, 0.35, 0.11
x31, x32, x33 = 0.29, 0.40, 0.24

A = np.array([
    [x11, x12, x13],
    [x21, x22, x23],
    [x31, x32, x33]
])
A

array([[0.19, 0.25, 0.65],
       [0.52, 0.35, 0.11],
       [0.29, 0.4 , 0.24]])

In [4]:
# Criando a matriz b
b1, b2, b3 = 310, 330, 360

b = np.array([b1, b2, b3])
b

array([310, 330, 360])

In [5]:
# Calculando as incógnitas.

x = np.linalg.solve(A, b)

F1 = x[0]
F2 = x[1]
F3 = x[2]

In [6]:
# Imprimindo os resultados
print('O resultado de F1 = {:.2f}'.format(F1), 'Kg/h')
print('O resultado de F2 = {:.2f}'.format(F2), 'Kg/h')
print('O resultado de F3 = {:.2f}'.format(F3), 'Kg/h')

O resultado de F1 = 119.40 Kg/h
O resultado de F2 = 712.69 Kg/h
O resultado de F3 = 167.91 Kg/h


In [7]:
# Conferindo os resultados.
z1 = 0.19*F1 + 0.25*F2 + 0.65*F3
z2 = 0.52*F1 + 0.35*F2 + 0.11*F3
z3 = 0.29*F1 + 0.40*F2 + 0.24*F3

# Imprimindo os resultados.
print(f'O resultado de b1 = {b1} e o resultado de z1 = {z1}')
print(f'O resultado de b2 = {b2} e o resultado de z2 = {z2}')
print(f'O resultado de b3 = {b3} e o resultado de z3 = {z3}')

O resultado de b1 = 310 e o resultado de z1 = 310.0
O resultado de b2 = 330 e o resultado de z2 = 330.0
O resultado de b3 = 360 e o resultado de z3 = 360.0


#### Aplicação industrial - Caso 1.

Este tipo de cálculo é de grande utilidade para Engenharia Química e Petroquímica em que deve ser projetado um reator contendo misturas <br>com concentrações específicas. Nesse exercício foi usado **álgebra** para determinar a concentração de um único reator usando o conhecimento <br> de balanços de massa visto em assuntos anteriores. Dessa forma, fica mais fácil a utilização de computador para a realização desse tipo de cálculo.


<img src="img/reator2.png" alt="UESC" style="width: 600px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Conjunto com Conexões de reatores.</strong></p>

__Informações__:

1. Estabelecer um volume de controle em cada reator.
2. Faça um balanço de massa em cada reator (entrada de fluxo positivo, saída de fluxo negativo).
3. Serão 5 equações e 5 incógitas ($c_1$, $c_2$, $c_3$, $c_4$, $c_5$)
4. Monte a Matriz: $Ax=b$
6. Cálcule a matriz inversa $A$.
7. Cálcule a incógnita $x$ - coloque os valores de saída separados ($c_1$, $c_2$, $c_3$, $c_4$, $c_5$)<br>
$c_1 = x[0,0]$ <br>
$c_2 = x[1,0]$ <br>
$c_3 = x[2,0]$ <br>
$c_4 = x[3,0]$ <br>
$c_5 = x[4,0]$ <br>
8. Confira seus cálculos substituindo os valores nas equações.



__Solução__:

__Primeiro Reator__:

<img src="img/reator3.png" alt="UESC" style="width: 450px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Balanço no reator C1.</strong></p>

Para o balanço de massa no primeiro reator de entrada, temos:

$$ Q_{01}c_{01} = 5 \ x \ 10 = 50$$

__Entrada = saída__

\begin{align*}
Q_{01}c_{01} + Q_{31}c_3 &= Q_{15}c_1 + Q_{12}c_1 \\
50 + c_3 &= 2c_1 + 3c_1 \\
-6c_1 + c_3 &= -50 \\
6c_1 - c_3 &= 50
\end{align*}


A equação acima corresponde ao balanço no primeiro reator.

__Segundo Reator__:

<img src="img/reator4.png" alt="UESC" style="width: 400px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Balanço no reator C2.</strong></p>

Balanço material no segundo reator.

$Entrada = saída$

\begin{align*}
Q_{12}c_1 = Q_{25}c_2 + Q_{23}c_2 + Q_{24}c_2 \\
3c_1 = c_2 + c_2 + c_2 \\
3c_1 = 3c_2 \\
3c_1 -  3c_2 = 0
\end{align*}


Equação para o segundo reator

__Terceiro Reator__:

<img src="img/reator5.png" alt="UESC" style="width: 550px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Balanço no reator C3.</strong></p>

Balançco material no terceiro reator.

$$ entrada = saída $$

\begin{align*}
Q_{03}c_{03} + Q_{23}c_2 = Q_{34}c_3 + Q_{31}c_3  \\
(8  \ x \ 20) + c_2 = 8c_3 + c_3  \\
160 + c_2 = 8c_3 + c_3 \\
160 = 9c_3 - c_2 \\
9c_3 - c_2 = 160  
\end{align*}

Equações para o terceiro reator.


__Quarto Reator__:

<img src="img/reator6.png" alt="UESC" style="width: 400px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Balanço no reator C4.</strong></p>

Balanço material no segundo reator.

\begin{align*}
Q_{24}c_2 + Q_{34}c_3 + Q_{54}c_5 = Q_{44}c_4 \\
c_2 + 8c_3 + 2c_5 = 11c_4 \\
c_2 + 8c_3 + 2c_5 - 11c_4 = 0 
\end{align*}

Equação para o quarto reator.

__Quinto Reator__:

<img src="img/reator7.png" alt="UESC" style="width: 550px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Balanço no reator C5.</strong></p>


Balanço material no quinto reator.

$$ Entrada = Saída $$

\begin{align*}
3c_1 + c_2= 2c_5 + 2c_5 \\
3c_1 + c_2 = 4c_5 \\
3c_1 + c_2 - 4c_5 = 0  
\end{align*}

Equação para o quinto reator.

Abaixo estão todas as equações dos cinco reatores.

\begin{align*}
6c_1 - c_3 = 50 \\
3c_1 -  3c_2 = 0 \\
9c_3 - c_2 = 160 \\
c_2 + 8c_3 + 2c_5 - 11c_4 = 0 \\
3c_1 + c_2 - 4c_5 = 0 
\end{align*}

<img src="img/tabela_reator_1.png" alt="UESC" style="width: 650px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Tabela com os dados calculados do balanço dos reatores.</strong></p>

Vamos criar um sistema matricial com os dados da Tabela acima de forma que: $A.\vec{x}=\vec{b}$

\begin{equation}
\begin{bmatrix}
6 & 0 & -1 & 0 & 0 \\
3 & -3 & 0 & 0 & 0 \\
0 & -1 & 9 & 0 & 0 \\
0 & 1 & 8 & -11 & 2 \\
3 & 1 & 0 & 0 & -4 \\
\end{bmatrix}
.
\begin{bmatrix}
c_1 \\
c_2 \\
c_3 \\
c_4 \\
c_5
\end{bmatrix}
=
\begin{bmatrix}
50 \\
0 \\
160 \\
0 \\
0
\end{bmatrix}
\end{equation}

A matriz $A$ tem a forma de uma matriz $5x5$, precisamos encontrar um modelo que possamos utilizar para resolução dessa matriz. 
<br>Vamos usar o modelo de matrizes **csr_matrix** para isso, precisamos criar uma matriz com: linhas, colunas e dados (row, col, data).

In [8]:
import numpy as np
from scipy import sparse
from scipy.sparse import csr_matrix

In [9]:
# Declarando as arrays.
row = np.array([0, 0, 1, 1, 2, 2, 3, 3, 3, 3, 4, 4, 4])
col = np.array([0, 2, 0, 1, 1, 2, 1, 2, 3, 4, 0, 1, 4])
data = np.array([6, -1, 3, -3, -1, 9, 1, 8, -11, 2, 3, 1, -4])

In [10]:
A_coord = sparse.coo_matrix((data, (row,col)), dtype=float)
print(A_coord)

<COOrdinate sparse matrix of dtype 'float64'
	with 13 stored elements and shape (5, 5)>
  Coords	Values
  (0, 0)	6.0
  (0, 2)	-1.0
  (1, 0)	3.0
  (1, 1)	-3.0
  (2, 1)	-1.0
  (2, 2)	9.0
  (3, 1)	1.0
  (3, 2)	8.0
  (3, 3)	-11.0
  (3, 4)	2.0
  (4, 0)	3.0
  (4, 1)	1.0
  (4, 4)	-4.0


Podemos transformar a matriz coordenada (COO) para matriz esparsa usando: **.toarray()**

In [11]:
A = sparse.coo_matrix((data, (row,col)), dtype=float).toarray()
print(A)

[[  6.   0.  -1.   0.   0.]
 [  3.  -3.   0.   0.   0.]
 [  0.  -1.   9.   0.   0.]
 [  0.   1.   8. -11.   2.]
 [  3.   1.   0.   0.  -4.]]


In [12]:
A = sparse.csr_matrix((data, (row, col)), shape = (5,5), dtype=float).toarray()
A

array([[  6.,   0.,  -1.,   0.,   0.],
       [  3.,  -3.,   0.,   0.,   0.],
       [  0.,  -1.,   9.,   0.,   0.],
       [  0.,   1.,   8., -11.,   2.],
       [  3.,   1.,   0.,   0.,  -4.]])

In [13]:
A_inv = np.linalg.inv(A)

In [14]:
b1, b2, b3, b4, b5 = 50, 0, 160, 0, 0

b = np.array([b1, b2, b3, b4, b5])

In [15]:
# Cálculo das incógnitas.
x = A_inv.dot(b)

c1 = x[0]
c2 = x[1]
c3 = x[2]
c4 = x[3]
c5 = x[4]

In [16]:
def line():
    print('-'*50)

line()
print('   RESULTADOS DAS CONCENTRAÇÕES' )
line()

print('O resultado de c1 = {:.2f}'.format(c1), 'mg/m3')
print('O resultado de c2 = {:.2f}'.format(c2), 'mg/m3')
print('O resultado de c3 = {:.2f}'.format(c3), 'mg/m3')
print('O resultado de c4 = {:.2f}'.format(c4), 'mg/m3')
print('O resultado de c5 = {:.2f}'.format(c5), 'mg/m3')
line()


--------------------------------------------------
   RESULTADOS DAS CONCENTRAÇÕES
--------------------------------------------------
O resultado de c1 = 11.51 mg/m3
O resultado de c2 = 11.51 mg/m3
O resultado de c3 = 19.06 mg/m3
O resultado de c4 = 17.00 mg/m3
O resultado de c5 = 11.51 mg/m3
--------------------------------------------------


Conferindo os resultados

In [17]:
z1 = 6*c1-c3
z3 = -c2+9*c3

In [18]:
line()
print('   CONFERINDO OS RESULTADOS DAS CONCENTRAÇÕES' )
line()

print(f'O resultado de b1 = {b1} e o resultado de z1 = {z1:.2f}')
print(f'O resultado de b3 = {b3} e o resultado de z3 = {z3:.2f}')
line()

--------------------------------------------------
   CONFERINDO OS RESULTADOS DAS CONCENTRAÇÕES
--------------------------------------------------
O resultado de b1 = 50 e o resultado de z1 = 50.00
O resultado de b3 = 160 e o resultado de z3 = 160.00
--------------------------------------------------


<div style="text-align: center; font-size: 12px; color: gray; margin-top: 40px;">
  Este notebook foi desenvolvido no âmbito do Grupo de Pesquisas em Modelagem Computacional da UESC.<br>
  Todos os direitos reservados © 2025
</div>