<div style="text-align: center;">

  <!-- Logotipo -->
  <img src="img/LogoUesc.png" alt="UESC" style="width: 60px; display: block; margin: 0 auto 5px auto;">

  <!-- Cabeçalho -->
  <div style="font-size: 20px;"><strong>UNIVERSIDADE ESTADUAL DE SANTA CRUZ - UESC</strong></div>
  <div style="font-size: 18px;">DEPARTAMENTO DE ENGENHARIAS E COMPUTAÇÃO</div>
  <div style="font-size: 18px;">ENGENHARIA QUÍMICA</div>

  <hr style="margin: 20px 0; border: 1px solid #0074B7;">

  <!-- Título do Trabalho -->
  <div style="font-size: 22px; font-weight: bold; margin-bottom: 10px;">Modelagem, Simulação e Otimização de Processos Químicos</div>
  <div style="font-size: 20px; font-weight: bold; margin-bottom: 10px;">Processo de separação de componentes químicos</div>

  <!-- Autor e orientador -->
  <div style="font-size: 18px;">Prof. Dr. E.R.Edwards</div>

<hr style="margin: 20px 0; border: 1px solid #0074B7;">
  <!-- Data -->
<!-- <div style="font-size: 16px; margin-top: 15px;">Ilhéus - BA, Abril de 2025</div> -->
</div>

__Exemplo Prático de Cálculo__ (Simplificado)<br>

Vamos trabalhar com uma matriz $3x3$ para ilustrar o processo, já que uma 5x5 teria muitas operações para fazer manualmente:

\begin{equation}
B =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\\nonumber 
\end{bmatrix}
\end{equation}

Para calcular o determinante $det(B)$, fazemos a expansão pela primeira linha:

\begin{equation}
B1 =
\begin{bmatrix}
5 & 6  \\
8 & 9 \\\nonumber 
\end{bmatrix}
= (5×9)−(6×8)=45−48=−3
\end{equation}

\begin{equation}
B2 = - 1
\begin{bmatrix}
5 & 6  \\
8 & 9 \\\nonumber 
\end{bmatrix}
=(4×9)−(6×7)=36−42=−6
\end{equation}

\begin{equation}
B3 = 3
\begin{bmatrix}
4 & 5  \\
7 & 8 \\\nonumber 
\end{bmatrix}
=(4×8)−(5×7)=32−35=−3
\end{equation}

Finalmente, substituímos esses valores na fórmula do determinante de $B$:
$$ det(B) - 1.(-3) - 2.(-6)+3.(-3) $$

$$ de(B) = -3 + 12 -9 = 0 $$

Portanto, o determinante da matriz $B$ é $0$.

A figura abaixo mostra uma coluna de separação de componentes de petróleo. Sabendo-se que os fluxos de entrada do metileno é de $30.0 Kg/s$, do etileno de $25.0 Kg/s$ e do propeno de $10.0 Kg/s$. Resolva o problema de forma computacional aplicando **Método Algébrico** para determinar os componentes $m_1$, $m_2$ e $m_3$ nas saídas da coluna de separação sabendo-se que as frações de cada componente estão representada no conjunto de matrizes $A.x=b$ abaixo.

\begin{equation}
	\begin{bmatrix}
		0.9 & 0.3  & 0.1 \\
		0.1 & 0.5  & 0.2 \\
		0.0 & 0.2  &0.7 \nonumber \\ 
	\end{bmatrix} 
	.
	\begin{bmatrix}
		m_1 \\
		m_2 \\
    	m_3 \\ 
	\end{bmatrix} 
	=
	\begin{bmatrix}
	30.0 \\
	25.0 \\
	10.0 \\ 
	\end{bmatrix}
\end{equation}

<img src="img/Figura_Sep_3x3.png" alt="UESC" style="width: 450px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Função Sigmoide.</strong></p>

__Passo 1__:

Vamos inicialmente cálcular o determinante da matriz $A$ - $det(A)$.

__Solução__: 

Vamos resolver a matriz: 

$$ A.x=b $$

para determinar as incógnitas $x$ de forma que:

$$ x = A^{-1}.b $$

Sendo $ A^{-1} $ a matriz inversa.

O cálculo da matriz inversa pode ser obtido por:

$$ A^{-1} = \frac{1}{det(A)},Adj(Ac) $$

Sendo:  
* $ det(A) $ o determinante da matriz $ A $, e 

* $ Adj(Ac) $ a matriz adjunta de $ A $ ou matriz transposta $ A^{T} $.

A matriz cofator $ A_c $ é dada por $ A_c = [c_{ij}] $, sendo $ c_{ij}= (-1)^{i+j}a_{ij} $

In [23]:
# Cálculo da matriz determinante de A - det(A).
# Matriz A:
a11, a12, a13 = 0.9, 0.3, 0.1
a21, a22, a23 = 0.1, 0.5, 0.2
a31, a32, a33 = 0.0, 0.2, 0.7

d = a11*((a22*a33)-(a23*a32))-a12*((a21*a33)-(a23*a31))+a13*((a21*a32)-(a22*a31))
d

0.25999999999999995

__Passo 2__: 

Vamos determinar a matriz cofator $A_c=[c_{ij}]$, aplicando para cada $c_{ij}=(-1)^{i+j}.a_{ij}$. 

 Para o elemento $a11$:
\begin{equation}
	\begin{bmatrix}
		{\color{red} a_{11}} & {\color{red} a_{12}}  & {\color{red} a_{13}}  \\
		{\color{red} a_{21}} & a_{22}  & a_{23}   \\
		{\color{red} a_{31}} & a_{32}  & a_{33}   \nonumber \\ 
	\end{bmatrix} 
	=>
	c_{11}=({-1})^{1+1}.
	\begin{bmatrix}
		 a_{22}  & a_{23}   \\
		 a_{32}  & a_{33}    \nonumber \\ 
	\end{bmatrix} 
\end{equation}

In [24]:
# matriz 2x2 do elemento a11:
a22, a23 = 0.5, 0.2
a32, a33 = 0.2, 0.7

# indices do elemento a11:
i = 1
j = 1

c11 = float((-1)**(i+j)*(a22*a33 - a23*a32))
c11

0.30999999999999994

Para o elemento $a_{12}$, temos:
\begin{equation}
	\begin{bmatrix}
		{\color{red} a_{11}}& {\color{red} a_{12}}  & {\color{red} a_{13}}  \\
		a_{21} & {\color{red} a_{22}}  & a_{23}   \\
		a_{31} & {\color{red} a_{32}}  & a_{33}    \nonumber \\ 
	\end{bmatrix} 
	=>
	c_{12}=({-1})^{1+2}.
	\begin{bmatrix}
		a_{21}  & a_{23}  \\
		a_{31}  & a_{33}   \nonumber \\ 
	\end{bmatrix} 
\end{equation}

In [25]:
# matriz 2x2 do elemento a12:
a21, a23 = 0.1, 0.2
a31, a33 = 0.0, 0.7

# indices do elemento a12:
i = 1
j = 2

c12 = float((-1)**(i+j)*(a21*a33 - a23*a31))
c12

-0.06999999999999999

Para o elemento $a_{13}$, temos:
\begin{equation}
	\begin{bmatrix}
		{\color{red} a_{11}}& {\color{red} a_{12}}  & {\color{red} a_{13}}  \\
		a_{21} & a_{22} & {\color{red} a_{23}}   \\
		a_{31} & a_{32}  &  {\color{red} a_{33}}    \nonumber \\ 
	\end{bmatrix} 
	=>
	c_{13}=({-1})^{1+3}.
	\begin{bmatrix}
		a_{21}  & a_{22}   \\
		a_{31}  & a_{32}    \nonumber \\ 
	\end{bmatrix} 
\end{equation}

In [26]:
# matriz 2x2 do elemento a13:
a21, a22 = 0.1, 0.5
a31, a32 = 0.0, 0.2

# indices do elemento a13:
i = 1
j = 3

c13 = float((-1)**(i+j)*(a21*a32 - a22*a31))
c13 

0.020000000000000004

Para o elemento $a_{21}$, temos:
\begin{equation}
	\begin{bmatrix}
		{\color{red}a_{11}}& a_{12}  & a_{13}  \\
		{\color{red} a_{21}} & {\color{red} a_{22}} & {\color{red} a_{23}}  \\
	{\color{red} a_{31}} & a_{32}  &  a_{33}    \nonumber \\ 
	\end{bmatrix} 
	=>
	c_{21}=({-1})^{2+1}.
	\begin{bmatrix}
		a_{12}  & a_{13}   \\
		a_{32}  & a_{33}    \nonumber \\ 
	\end{bmatrix} 
\end{equation}


In [27]:
# matriz 2x2 do elemento a21:
a12, a13 = 0.3, 0.1
a32, a33 = 0.2, 0.7

# indices do elemento a21:
i = 2
j = 1

c21 = float((-1)**(i+j)*(a12*a33 - a13*a32))
c21 

-0.19

Para o elemento $a_{22}$, temos:
\begin{equation}
	\begin{bmatrix}
		a_{11}& {\color{red} a_{12}}  & a_{13}  \\
		{\color{red} a_{21}} & {\color{red} a_{22}} & {\color{red} a_{23}}  \\
		a_{31} & {\color{red} a_{32}}  &  a_{33}    \nonumber \\ 
	\end{bmatrix} 
	=>
	c_{22}=({-1})^{2+2}.
	\begin{bmatrix}
		a_{11}  & a_{13}   \\
		a_{31}  & a_{33}    \nonumber \\ 
	\end{bmatrix} 
\end{equation}

In [28]:
# matriz 2x2 do elemento a22:
a11, a13 = 0.9, 0.1
a31, a33 = 0.0, 0.7

# indices do elemento a22:
i = 2
j = 2

c22 = float((-1)**(i+j)*(a11*a33 - a13*a31))
c22 

0.63

Para o elemento $a_{23}$, temos:
\begin{equation}
	\begin{bmatrix}
		a_{11}& a_{12}  & {\color{red} a_{13}}  \\
		{\color{red} a_{21}} & {\color{red} a_{22}} & {\color{red} a_{23}}  \\
		a_{31} & a_{32}  &  {\color{red} a_{33}}    \nonumber \\ 
	\end{bmatrix} 
	=>
	c_{23}=({-1})^{2+3}.
	\begin{bmatrix}
		a_{11}  & a_{12}   \\
		a_{31}  & a_{32}    \nonumber \\ 
	\end{bmatrix} 
\end{equation}

In [29]:
# matriz 2x2 do elemento a23:
a11, a12 = 0.9, 0.3
a31, a32 = 0.0, 0.2

# indices do elemento a23:
i = 2
j = 3

c23 = float((-1)**(i+j)*(a11*a32 - a12*a31))
c23 

-0.18000000000000002

Para o elemento $a_{31}$, temos:
\begin{equation}
	\begin{bmatrix}
		{\color{red} a_{11}}& a_{12}  & a_{13}  \\
		{\color{red} a_{21}} & a_{22} & a_{23}  \\
		{\color{red} a_{31}} & {\color{red} a_{32}}  &  {\color{red} a_{33}}    \nonumber \\ 
	\end{bmatrix} 
	=>
	c_{31}=({-1})^{3+1}.
	\begin{bmatrix}
		a_{12}  & a_{13}   \\
		a_{22}  & a_{23}    \nonumber \\ 
	\end{bmatrix} 
\end{equation}

In [30]:
# matriz 2x2 do elemento a31:
a12, a13 = 0.3, 0.1
a22, a23 = 0.5, 0.2

# indices do elemento a31:
i = 3
j = 1

c31 = float((-1)**(i+j)*(a12*a23 - a13*a22))
c31 

0.009999999999999995

Para o elemento $a_{32}$, temos:
\begin{equation}
	\begin{bmatrix}
		a_{11}& {\color{red} a_{12}} & a_{13}  \\
		a_{21} & {\color{red} a_{23}} & a_{23}  \\
		{\color{red} a_{31}} & {\color{red} a_{32}}  &  {\color{red} a_{33}}    \nonumber \\ 
	\end{bmatrix} 
	=>
	c_{32}=({-1})^{3+2}.
	\begin{bmatrix}
		a_{11}  & a_{13}   \\
		a_{21}  & a_{23}    \nonumber \\ 
	\end{bmatrix} 
\end{equation}

In [31]:
# matriz 2x2 do elemento a32:
a11, a13 = 0.9, 0.1
a21, a23 = 0.1, 0.2

# indices do elemento a32:
i = 3
j = 2

c32 = float((-1)**(i+j)*(a11*a23 - a13*a21))
c32 

-0.17

Para o elemento $a_{33}$, temos:
\begin{equation}
	\begin{bmatrix}
		a_{11}& a_{12} & {\color{red} a_{13}}  \\
		a_{21} & a_{22} & {\color{red} a_{23}}  \\
		{\color{red} a_{31}} & {\color{red} a_{32}}  &  {\color{red} a_{33}}    \nonumber \\ 
	\end{bmatrix} 
	=>
	c_{33}=({-1})^{3+3}.
	\begin{bmatrix}
		a_{11}  & a_{12}   \\
		a_{21}  & a_{22}    \nonumber \\ 
	\end{bmatrix} 
\end{equation}

In [32]:
# matriz 2x2 do elemento a33:
a11, a12 = 0.9, 0.3
a21, a22 = 0.1, 0.5

# indices do elemento a33:
i = 3
j = 3

c33 = float((-1)**(i+j)*(a11*a22 - a12*a21))
c33 

0.42000000000000004

##### Montagem da matriz dos cofatores, $A_c$.

\begin{equation}
	A_c = 
	\begin{bmatrix}
		c_{11} & c_{12}  & c_{13} \\
		c_{21} & c_{22}  & c_{23} \\
		c_{31} & c_{33}  & c_{33} \nonumber \\ 
	\end{bmatrix} 
\end{equation}

In [33]:
import numpy as np

# Matriz cofatores - Ac
Ac = np.array([[c11, c12, c13],
     [c21, c22, c23],
     [c31, c32, c33]])
Ac

array([[ 0.31, -0.07,  0.02],
       [-0.19,  0.63, -0.18],
       [ 0.01, -0.17,  0.42]])

__Cálculo da inversa da matriz $A_{ij}$__.

A inversa da matriz cofator $A^T$ (matriz transposta) é feita transformando linhas em colunas na matriz. 
Vamos fazer essa transformação calculando algebricamente, mas depois vamos aprender como fazer essa transformação usando o Numpy.

In [34]:
AT = np.array([[c11, c21, c31],
     [c12, c22, c32],
     [c13, c23, c33]])
AT

array([[ 0.31, -0.19,  0.01],
       [-0.07,  0.63, -0.17],
       [ 0.02, -0.18,  0.42]])

__Cálculo da matriz inversa $A^{-1}$__

Vamos aplicar a expressão abaixo para calcular a matriz inversa.

$$A^{-1} = \frac{1}{det(A)}.A^T$$

In [35]:
A_inv = np.array([[c11/d , c21/d , c31/d], 
                  [c12/d , c22/d , c32/d],
                  [c13/d, c23/d, c33/d]])             
A_inv                 

array([[ 1.19230769, -0.73076923,  0.03846154],
       [-0.26923077,  2.42307692, -0.65384615],
       [ 0.07692308, -0.69230769,  1.61538462]])

In [36]:
# Cálculo da matriz inversa.
#import numpy as np
#A_inv = D * np.array(AT)
#A_inv

__Cálculo do valor de b__

In [37]:
b = np.array([30.0, 25.0, 10.0])
b

array([30., 25., 10.])

In [38]:
# Cálculo de x=A^-1.b usando método algébrico.
# Extraindo os valores de b
b1=b[0]
b2=b[1]
b3=b[2]

# Cálculo de x.

m1 = A_inv[0][0]*b1 + A_inv[0][1]*b2 + A_inv[0][2]*b3
x1 = print('O valor de m1 = {:.2f}'.format(m1), 'Kg/s') 

m2 = A_inv[1][0]*b1 + A_inv[1][1]*b2 + A_inv[1][2]*b3
x2 = print('O valor de m2 = {:.2f}'.format(m2), 'Kg/s') 

m3 = A_inv[2][0]*b1 + A_inv[2][1]*b2 + A_inv[2][2]*b3
x3 = print('O valor de m3 = {:.2f}'.format(m3), 'Kg/s') 

O valor de m1 = 17.88 Kg/s
O valor de m2 = 45.96 Kg/s
O valor de m3 = 1.15 Kg/s


__Conferindo os resultados, temos__:

In [39]:
# 0.9*m1 + 0.3*m2 + 0.1*m3 = 30.0
z1 = 0.9*m1 + 0.3*m2 + 0.1*m3
# 0.1*m1 + 0.5*m2 + 0.2*m3 = 25.0
z2 = 0.1*m1 + 0.5*m2 + 0.2*m3
#   0 +   0.2*m2 + 1.0*m3 = 10.0
z3 = 0.2*m2 + 1.0*m3

# Conferindo os resultados.
z1 = print('O valor de b1 = 30.0 e o z1 = {:.2f}'.format(z1), 'Kg/s') 
z2 = print('O valor de b2 = 25.0 e o z2 = {:.2f}'.format(z2), 'Kg/s')
z3 = print('O valor de b3 = 10.0 e o z2 = {:.2f}'.format(z3), 'Kg/s')

O valor de b1 = 30.0 e o z1 = 30.00 Kg/s
O valor de b2 = 25.0 e o z2 = 25.00 Kg/s
O valor de b3 = 10.0 e o z2 = 10.35 Kg/s


__Agora vamos fazer o mesmo cálculo usando a biblioteca Numpy__.

Dentro da biblioteca Numpy possui a **Algebra Linear** (*linalg*) que possui todos esses códigos, o que possibilita a resolução com poucas linhas de código.

In [40]:
import numpy as np
import numpy.linalg as nl

# Vamos criar a matriz A
A = np.array([[0.9, 0.3, 0.1],
              [0.1, 0.5, 0.2],
              [0.0, 0.2, 0.7]
              ])

inversa_A = np.linalg.inv(A)

# Vamos criar a matriz do lado direito - b
b = np.array([30.0, 25.0, 10.0])

# Agora vamos resolver o sistema linear usando np.solve()
x = nl.solve(A, b)
# Também poderiamos ter usado o código abaixo.
# x = np.dot(A_inv, b) 

# Extraindo os valores de x da lista:
ma1 = x[0]
ma2 = x[1]
ma3 = x[2]

In [41]:
inversa_A

array([[ 1.19230769, -0.73076923,  0.03846154],
       [-0.26923077,  2.42307692, -0.65384615],
       [ 0.07692308, -0.69230769,  1.61538462]])

In [42]:
# Cálculo de x.
resposta_m1 = print('O valor de m1 = {:.2f}'.format(ma1), 'Kg/s') 
resposta_m2 = print('O valor de m2 = {:.2f}'.format(ma2), 'Kg/s') 
resposta_m3 = print('O valor de m3 = {:.2f}'.format(ma3), 'Kg/s')

O valor de m1 = 17.88 Kg/s
O valor de m2 = 45.96 Kg/s
O valor de m3 = 1.15 Kg/s


__Vamos conferir os resultados usando a biblioteca Numpy__.

In [43]:
# 0.9*m1 + 0.3*m2 + 0.1*m3 = 30.0
k1 = 0.9*ma1 + 0.3*ma2 + 0.1*ma3
# 0.1*m1 + 0.5*m2 + 0.2*m3 = 25.0
k2 = 0.1*ma1 + 0.5*ma2 + 0.2*ma3
#   0 +   0.2*m2 + 1.0*m3 = 10.0
k3 = 0.2*ma2 + 1.0*ma3

# Conferindo os resultados.
k1 = print('O valor de b1 = 30.0 e o k1 = {:.2f}'.format(k1), 'Kg/s') 
k2 = print('O valor de b2 = 25.0 e o k2 = {:.2f}'.format(k2), 'Kg/s')
k3 = print('O valor de b3 = 10.0 e o k2 = {:.2f}'.format(k3), 'Kg/s')

O valor de b1 = 30.0 e o k1 = 30.00 Kg/s
O valor de b2 = 25.0 e o k2 = 25.00 Kg/s
O valor de b3 = 10.0 e o k2 = 10.35 Kg/s


__Poderiamos ter usado o código abaixo para calcular x__.

In [44]:
x = np.dot(A_inv, b) 
x

array([17.88461538, 45.96153846,  1.15384615])

<div style="text-align: center; font-size: 12px; color: gray; margin-top: 40px;">
  Este notebook foi desenvolvido no âmbito do Grupo de Pesquisas em Modelagem Computacional da UESC.<br>
  Todos os direitos reservados © 2025
</div>