<div style="text-align: center;">

  <!-- Logotipo -->
  <img src="img/LogoUesc.png" alt="UESC" style="width: 60px; display: block; margin: 0 auto 5px auto;">

  <!-- Cabeçalho -->
  <div style="font-size: 20px;"><strong>UNIVERSIDADE ESTADUAL DE SANTA CRUZ - UESC</strong></div>
  <div style="font-size: 18px;">DEPARTAMENTO DE ENGENHARIAS E COMPUTAÇÃO</div>
  <div style="font-size: 18px;">ENGENHARIA QUÍMICA</div>

  <hr style="margin: 20px 0; border: 1px solid #0074B7;">

  <!-- Título do Trabalho -->
  <div style="font-size: 22px; font-weight: bold; margin-bottom: 10px;">Modelagem, Simulação e Otimização de Processos Químicos</div>
  <div style="font-size: 20px; font-weight: bold; margin-bottom: 10px;">Introdução a Métodos Computacionais na Engenharia Química</div>

  <!-- Autor e orientador -->
  <div style="font-size: 18px;">Prof. Dr. E.R.Edwards</div>

  <!-- Data -->
<!-- <div style="font-size: 16px; margin-top: 15px;">Ilhéus - BA, Abril de 2025</div> -->
</div>

Muitos cálculos de controle de processos  em que possuem várias entradas e várias saídas resolvemos utilizando métodos matriciais. Na aula de hoje vamos aprender como calcular matrizes aplicando métodos computacionais.

### Definição de Matrizes

**Definição**: Chama-se matriz de ordem $m$ por $n$ a um quadrado de $mxn$ elementos dispostos em $m$ linhas e $n$ colunas.

Seja a matriz:


\begin{equation}	
	A= 
	\begin{bmatrix}
		a_{11} &  a_{12}  \\
		a_{21} &  a_{22} \nonumber \\ 
	\end{bmatrix}_{mxn} 
\end{equation}

em que m refere-se a linhas e n a colunas.

Se o número de linhas for igual ao número de colunas dizemos que a matriz é quadrada.

**NOTAÇÃO**: Cada elemento da matriz esta afetada por dois índices: $a_{ij}$ tal que:

$$ A=[a_{ij}]_{mxn} $$

* $A$ ... é a Matriz
* $a$ ...é o número;
* $i$ ... é a posição da linha;
* $j$ ... é a posição da coluna

### Dedução
A figura abaixo mostra dois vetores, sendo o primeiro com distância $c$ no eixo $x$ e $d$ no eixo $y$ e o segundo com distância $a$ no eixo $x$ e $b$ no eixo $y$. Se prolongarmos a origem do primeiro vetor para ponta final do segundo vetor e se fizermos o mesmo com o segundo vetor, teremos uma área formada pelos vetores e seus prolongamentos. Como podemos determinar essa área? A melhor forma de calcularmos essa área é determinarmos, inicialmente, a área total do retângulo formada pela multiplicação da distância em $x$ por $y$.

<img src="img/fig_vetor_2x2.png" alt="UESC" style="width: 800px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Cálculo de área após prolongamento de vetores .</strong></p>

#### Cálculo da área do retângulo
$A_t =(a+c).(b+d)$

#### Cálculo das áreas externas.

$A_e = 2A_1 + 2\frac{B_1}{2} + 2\frac{C_1}{2} $

e substituindo os valores para cada área, temos:

$ A_e = 2.b.c + 2.\frac{a.b}{2} +  2.\frac{c.d}{2} $

Então a área dentro da geometria formada pelo prolongamento dos vetores será dada por ($A_v$):

$ A_v = A_t - A_e $ 

$ A_v = a.b + a.d + b.c + c.d - 2.c.b - 2.\frac{a.b}{2} -  2.\frac{c.d}{2} $ 

Fazendo o algebrismo, temos:

$A_v = a.b + a.d + b.c + c.d - 2.b.c - a.b -  c.d $

$A_v =  a.d  - b.c  $

Dessa forma, a área de um retângulo irregular pode ser calculada pelo determinante abaixo:  

$$
\begin{equation}	
	A_v= 
	\begin{bmatrix}
		a &  b \\
		c &  d \nonumber \\ 
	\end{bmatrix} 
	=a.d-b.d	
\end{equation}
$$

#### Inversa de uma matriz 2x2.

Agora vamos analisar como obter a inversa dessa matriz $2x2$. Essa matriz só será inversível se:  $a.d-b.d \neq 0$
		
$$
\begin{equation}
A^{-1}= \frac{1}{ad-bc}.
\begin{bmatrix}
d &  -b \\
-c &  a \nonumber \\ 
\end{bmatrix} 
\end{equation}
$$

Multiplicando por cada elemento da matriz, temos:

$$
\begin{equation}	
A^{-1}= 
\begin{bmatrix}
\frac{d}{ad-bc} &  \frac{-b}{ad-bc} \\
\frac{-c}{ad-bc} &  \frac{a}{ad-bc} \nonumber \\ 
\end{bmatrix} 
\end{equation}
$$

### Exemplo:
Seja a matriz $2x2$ abaixo, deduza sua inversa,  $A^{-1}$;  e em seguida faça um programa em Python para resolver essa matriz.  Confira o resultado com a obtenção  da matriz identidade $I$. Imprima todos os resultados.

$$
 \begin{equation}	
	 	A =
        \begin{bmatrix}
		 		a_{11} &  a_{12} \\
		 		a_{21} &  a_{22} \nonumber \\ 
		 	\end{bmatrix} 
        =
	 	\begin{bmatrix}
		 		1 &  2 \\
		 		1 &  3 \nonumber \\ 
		 	\end{bmatrix} 
	 \end{equation}
$$     

Vamos aplicar a equação acima para calcular a inversa da matriz $A$:

$$
 \begin{equation}	
	 	A^{-1}= \frac{1}{(1)(3)-(2)(1)}.
	 	\begin{bmatrix}
		 		3 &  -2 \\
		 		-1 &  1 \nonumber \\ 
		 	\end{bmatrix} 
	 \end{equation}
$$

$$
 \begin{equation}	
	 	A^{-1} = 
	 	\begin{bmatrix}
		 		3 &  -2 \\
		 		-1 &  1 \nonumber \\ 
		 	\end{bmatrix} 
	 \end{equation}
$$

In [1]:
# Resolução computacional da inversa de uma matriz A^-1.
a11, a12 = 1, 2
a21, a22 = 1, 3

# Cálculo do determinante.

D = 1/(a11*a22 - a12*a21)
D

1.0

#### Conferindo os resultados

Na matemática, se multiplicarmos "$a$" pela sua inversa "$a^{-1}$", teremos $a.\frac{1}{a} =  1$. Agora, se multiplicarmos a matriz $A$ pela sua inversa $A^{-1}$, teremos uma matriz identidade $I$:

$$A.A^{-1} = A.\frac{1}{A}=I$$
=
\begin{bmatrix}
1 &  0 \\
0 &  1 \nonumber \\ 
\end{bmatrix} 


Dessa forma, o resultado da inversa da matriz $A$ estará correto.
$
 \begin{equation}	
	 	\begin{bmatrix}
		 		1 &  2 \\
		 		1 &  3 \nonumber \\ 
		 	\end{bmatrix} 
	 	.
	 	\begin{bmatrix}
		 		3 &  -2 \\
		 	-1 &  1 \nonumber \\ 
		 	\end{bmatrix} 
	 	=
	 	\begin{bmatrix}
		 	(3-2)  &  (-2+2)  \\
		 	(3-3) &  (-2+3) \nonumber \\ 
		 	\end{bmatrix} 
	 	=
	 	\begin{bmatrix}
		 		1  &  0  \\
		 	    0  &  1  \nonumber \\ 
		 	\end{bmatrix} 
	 	=
	 	I
	 \end{equation}
 $

Vamos determinar a Matriz identidade everificar se o resultado da matriz inversa "$A^{-1}$" esta correta. 

In [2]:
import numpy as np

# Cálculo da Matriz A.
A = np.array([
    [a11, a12],
    [a21, a22]])
A

array([[1, 2],
       [1, 3]])

In [3]:
# Cálculo da inversa da Matriz A.

A_inv = (1/(a11*a22 - a12*a21))*np.array([[a22, -a12],
                                         [-a21, a11]])
                                         
A_inv

array([[ 3., -2.],
       [-1.,  1.]])

In [4]:
# Multiplicação da Matriz A e sua Inversa.

I = np.dot(A, A_inv)
I

array([[1., 0.],
       [0., 1.]])

Logo o resultado da Matriz inversa esta correto.

#### Adição de matrizes

A soma de duas matrizes $A=[a_{ij}]$ e $B=[b_{ij}]$ de ordem $(m,n)$ é uma matriz $C=[c_{ij}]$ tal que:

$$c_{ij} =  a_{ij} + b_{ij}$$

\begin{equation}	
	A= 
	\begin{bmatrix}
		a_{11} &  a_{12}  &  a_{13} \\
        a_{21} &  a_{22}  &  a_{23} \\
		a_{31} &  a_{32}  &  a_{33} \\ \nonumber 
	\end{bmatrix} 
    B= 
	\begin{bmatrix}
		b_{11} &  b_{12}  &  b_{13} \\
        b_{21} &  b_{22}  &  b_{23} \\
		b_{31} &  b_{32}  &  b_{33} \\ \nonumber 
	\end{bmatrix}
\end{equation}

\begin{equation}	
	C= 
	\begin{bmatrix}
		a_{11}+b_{11} &  a_{12}+b_{12}  &  a_{13}+b_{13} \\
        a_{21}+b_{21} &  a_{22}+b_{22}  &  a_{23}+b_{23} \\
		a_{31}+b_{31} &  a_{32}+b_{32}  &  a_{33}+b_{33} \\ \nonumber 
	\end{bmatrix}
    =
    \begin{bmatrix}
		c_{11} &  c_{12}  &  c_{13} \\
        c_{21} &  c_{22}  &  c_{23} \\
		c_{31} &  c_{32}  &  c_{33} \\ \nonumber 
	\end{bmatrix} 
\end{equation}

#### Exemplo: 
Cálcule a soma das matrizes abaixo tal que: $C=A+B$

\begin{equation}	
	A= 
	\begin{bmatrix}
		5 &  -2  &  3 \\
        2 &  1  &  -4 \\
		1 &  0  &  2 \\ 
        3 &  -1  &  4 \\ \nonumber  
	\end{bmatrix}
    B= 
	\begin{bmatrix}
		-2 &  1  &  3 \\
        4 &  2  &  5 \\
        0 &  2  &  -2 \\
		-3 &  0  &  5 \\ \nonumber  
	\end{bmatrix}
\end{equation}

**Resposta**:

\begin{equation}	
	C= 
	\begin{bmatrix}
		3 &  -1  &  6 \\
        6 &  3  &  1 \\
		1 &  2 &  0 \\ 
        0 &  -1  &  9 \\ \nonumber  
	\end{bmatrix}
\end{equation}



In [5]:
# ---Dados da matriz A
a11, a12, a13 = 5, -2, 3
a21, a22, a23 = 2, 1, -4
a31, a32, a33 = 1, 0, 2
a41, a42, a43 = 3, -1, 4

# --- Dados da matriz B
b11, b12, b13 = -2, 1, 3
b21, b22, b23 = 4, 2, 5
b31, b32, b33 = 0, 2, -2
b41, b42, b43 = -3, 0, 5

In [6]:
# Cálculo da matriz C
C = [
    [a11+b11, a12+b12, a13+b13],
    [a21+b21, a22+b22, a23+b23],
    [a31+b31, a32+b32, a33+b33],
    [a41+b41, a42+b42, a43+b43]
]
C

[[3, -1, 6], [6, 3, 1], [1, 2, 0], [0, -1, 9]]

#### Subtração de Matrizes

A diferência de duas matrizes $A-B$ de ordem $(mxn)$ é uma matriz $C$ tal que:

$$ c_{ij} = a_{ij} - b_{ij}$$

\begin{equation}	
	A= 
	\begin{bmatrix}
		a_{11} &  a_{12}  &  a_{13} \\
        a_{21} &  a_{22}  &  a_{23} \\
		a_{31} &  a_{32}  &  a_{33} \\ \nonumber  
	\end{bmatrix} 
    \ 
    B= 
	\begin{bmatrix}
		b_{11} &  b_{12}  &  b_{13} \\
        b_{21} &  b_{22}  &  b_{23} \\
		b_{31} &  b_{32}  &  b_{33} \\ \nonumber  
	\end{bmatrix}
\end{equation}

\begin{equation}	
	C= 
	\begin{bmatrix}
		a_{11}-b_{11} &  a_{12}-b_{12}  &  a_{13}-b_{13} \\
        a_{21}-b_{21} &  a_{22}-b_{22}  &  a_{23}-b_{23} \\
		a_{31}-b_{31} &  a_{32}-b_{32}  &  a_{33}-b_{33} \\ \nonumber 
	\end{bmatrix}
    =
    \begin{bmatrix}
		c_{11} &  c_{12}  &  c_{13} \\
        c_{21} &  c_{22}  &  c_{23} \\
		c_{31} &  c_{32}  &  c_{33} \\ \nonumber  
	\end{bmatrix} 
\end{equation}

**Resposta**: Use os mesmos dados das matrizes anteriores.

\begin{equation}	
	C= 
	\begin{bmatrix}
		7 &  -3  &  0 \\
        -2 &  -1  &  -9 \\
		1 &  -2 &  4 \\ 
        6 &  -1  &  -1 \\ \nonumber  
	\end{bmatrix}
\end{equation}


In [7]:
# dados de entrada repetidos do problema anterior.
D = [
    [a11-b11, a12-b12, a13-b13],
    [a21-b21, a22-b22, a23-b23],
    [a31-b31, a32-b32, a33-b33],
    [a41-b41, a42-b42, a43-b43]
]
D

[[7, -3, 0], [-2, -1, -9], [1, -2, 4], [6, -1, -1]]

### Produto de matriz por um escalar
Se $\lambda$ é um escalar, o produto de uma matriz $A$ por este escalar é uma matriz $B$ tal que:

$$ b_{ij} =  \lambda a_{ij} $$

\begin{equation}	
	B= \lambda. 
	\begin{bmatrix}
		a_{11} &  a_{12}  &  a_{13} \\
        a_{21} &  a_{22}  &  a_{23} \\
		a_{31} &  a_{32}  &  a_{33} \\ \nonumber 
	\end{bmatrix} 
    =
    \begin{bmatrix}
		\lambda.a_{11} &  \lambda.a_{12}  &  \lambda.a_{13} \\
        \lambda.a_{21} &  \lambda.a_{22}  &  \lambda.a_{23} \\
		\lambda.a_{31} &  \lambda.a_{32}  &  \lambda.a_{33} \\ \nonumber 
	\end{bmatrix}   
\end{equation}

**Exemplo**
\begin{equation}	
	B= 5. 
	\begin{bmatrix}
		4 &  -2  &  1 \\
        3 &  -5  &  0  \\ \nonumber 
	\end{bmatrix} 
  \end{equation}
  
 **Resposta**
\begin{equation}	
	B=  
	\begin{bmatrix}
		20 &  -10  &  5 \\
        15 &  -25  &  0  \\ \nonumber 
	\end{bmatrix} 
  \end{equation}

In [8]:
k = 5

a11, a12, a13 = 4, -2, 1
a21, a22, a23 = 3, -5, 0

B = [
    [k*a11, k*a12, k*a13],
    [k*a21, k*a22, k*a23],
   ]

B

[[20, -10, 5], [15, -25, 0]]

In [9]:
import numpy as np

C = k*np.array([
    [a11, a12, a13],
    [a21, a22, a23]
])

C

array([[ 20, -10,   5],
       [ 15, -25,   0]])

#### Multiplicação de matrizes.

A multiplicação de matrizes é feita multiplicando a linha da primeira matriz pela coluna da segunda matriz. 

**Observação**

* A multiplicação de matrizes só é possível quando o  número de colunas da primeira matriz for igual ao número de linhas da segunda matriz, ou seja $A_{(1,{\color{red}5})}$ então $B_{({\color{red}5},1)}$. Se a multiplicação existir, a matriz produto terá a quantidade de linhas da primeira matriz e a quantidade de colunas da segunda matriz. 

Seja a matriz $A_{(1,5)}$ e $B_{(5,1)}$ calcule $C=A.B$


\begin{equation}	
	A= 
	\begin{bmatrix}
	a_{11} &  a_{12} &  a_{13} &  a_{14} &  a_{15} \nonumber \\ 
	\end{bmatrix} 
    \
    \
    B
    =
    \begin{bmatrix}
		b_{11}  \\
        b_{12}  \\
        b_{13}  \\
        b_{14}  \\
		b_{15}  \\ \nonumber \\ 
	\end{bmatrix} 
\end{equation}

$$c_{11} = a_{11}.b_{11} +  a_{12}.b_{12} + a_{13}.b_{13} +a_{14}.b_{14} +a_{15}.b_{15} $$

**Exemplo 1**

Cálcule $C$ sabendo-se que: 

\begin{equation}	
	A= 
	\begin{bmatrix}
	4 &  3 &  2 &  5  \nonumber 
	\end{bmatrix} 
    B
    =
    \begin{bmatrix}
		6  \\
        4  \\
        5  \\
        3  \\ \nonumber  
	\end{bmatrix} 
\end{equation}

**Resposta**
$C = 4.6 + 3.4 + 2.5 + 5.3 = 61$

In [10]:
a11, a12, a13, a14 = 4, 3, 2, 5
b11, b12, b13, b14 = 6, 4, 5, 3

C = a11*b11 + a12*b12 + a13*b13 + a14*b14
C

61

**Exemplo 2**

Sabendo-se que matriz $A$ e $B$ são dados abaixo, calcule a matriz $C=A.B$ 

\begin{equation}
      A = 
     \begin{bmatrix}
     2 & 3 \\
     4 & 6 \\
     \end{bmatrix} 
     \
     \
    B = 
     \begin{bmatrix}
     1 & 3 & 0 \\
     2 & 1 & 1 \\
     \end{bmatrix}
\end{equation}

**Solução**:
Para calcular $C$ de fórma computacional, vamos colocar as matrizes $A$ e $B$ com notações tais que: $A=[a_{i,j}]$ e $B=[b_{i,j}]$.

\begin{equation}
 \begin{bmatrix}
     a_{11} & a_{12} \\
     a_{21} & a_{22} \\
     \end{bmatrix}  
    .
     \begin{bmatrix}
     b_{11} & b_{12} & b_{13} \\
     b_{21} & b_{22} & b_{23} \\
     \end{bmatrix}
     =
     \begin{bmatrix}
     a_{11}.b_{11} + a_{12}.b_{21} & a_{11}.b_{12} + a_{12}.b_{22}  & a_{11}.b_{13} + a_{12}.b_{23} \\
     a_{21}.b_{11} + a_{22}.b_{21} & a_{21}.b_{12} + a_{22}. b_{22} & a_{21}.b_{13} + a_{22}.b_{23} \\
     \end{bmatrix}  
\end{equation}

**Resposta**:
Logo a matriz $C$ será:

\begin{equation}
C = 
\begin{bmatrix}
8  & 9  & 3 \\
16 & 18 & 6 \\
\end{bmatrix}
=
\begin{bmatrix}
c_{11} & c_{12} & c_{13} \\
c_{21} & c_{22} & c_{23} \\
\end{bmatrix}
\end{equation}

In [11]:
# Dados da matriz A:
a11, a12 = 2, 3
a21, a22 = 4, 6

# Dados da matriz B:
b11, b12, b13 = 1, 3, 0
b21, b22, b23 = 2, 1, 1

# Primeira linha
c11 = a11*b11 + a12*b21
c12 = a11*b12 + a12*b22 
c13 = a11*b13 + a12*b23

# Segunda linha
c21 = a21*b11 + a22*b21 
c22 = a21*b12 + a22*b22
c23 = a21*b13 + a22*b23

C = [
    [c11, c12, c13],
    [c21, c22, c23]
    ]

C

[[8, 9, 3], [16, 18, 6]]

#### Dedução

Seja a matriz $A$ e $B$, calcule a matriz $C$.

$$C_{i,j} = \sum_k A_{i,k}.B_{k,j} $$

\begin{equation}
A =
    \begin{bmatrix}
      a_{11} &  a_{12}  &  a_{13}  \\
      a_{21} &  a_{22}  &  a_{23}  \\
	  a_{31} &  a_{32}  &  a_{33} \nonumber 
    \end{bmatrix}
    \
    \
    B =
    \begin{bmatrix}
      b_{11} &  b_{12}  &  b_{13}  \\
      b_{21} &  b_{22}  &  b_{23}  \\
	  b_{31} &  b_{32}  &  b_{33} \nonumber 
    \end{bmatrix}
   \end{equation}

\begin{equation}
C = A.B = 
    \begin{bmatrix}
       a_{11}.b_{11}+a_{12}.b_{21}+a_{13}.b_{31}  &  a_{11}.b_{12}+a_{12}.b_{22}+a_{13}.b_{32}  & a_{11}.b_{13}+a_{12}.b_{23}+a_{13}.b_{33}\\
       a_{21}.b_{11}+a_{22}.b_{21}+a_{23}.b_{31}  &  a_{21}.b_{12}+a_{22}.b_{22}+a_{23}.b_{32}  & a_{21}.b_{13}+a_{22}.b_{23}+a_{23}.b_{33}\\
	   a_{31}.b_{11}+a_{32}.b_{21}+a_{33}.b_{31}  &  a_{31}.b_{12}+a_{32}.b_{22}+a_{33}.b_{32}  & a_{31}.b_{13}+a_{32}.b_{23}+a_{33}.b_{33} \nonumber 
    \end{bmatrix}
    = 
    \begin{bmatrix}
     c_{11} &  c_{12} &  c_{13}  \\
	 c_{21} &  c_{22} &  c_{23} \\
     c_{31} &  c_{32} &  c_{33}  \nonumber 
    \end{bmatrix}
\end{equation}


#### Exemplo:

Cálcule a matriz $C = A.B$ dados por:

\begin{equation}
A =
    \begin{bmatrix}
      2 & 1 &  2  \\
      3 &  2 &  2  \\
	  1 &  1 &  2 \nonumber 
    \end{bmatrix}
    \
    \
    B =
     \begin{bmatrix}
      1 &  5 &  3  \\
      4 &  2 &  1  \\
	  1 &  2 &  2 \nonumber 
    \end{bmatrix}
\end{equation}

#### Resposta

\begin{equation}
C =
    \begin{bmatrix}
      8   &  16  &  11  \\
      13  &  23  &  15 \\
	  7   &  11  &  8  \nonumber 
    \end{bmatrix}
\end{equation}


In [12]:
# Dados da matriz A:
a11, a12, a13 = 2, 1, 2
a21, a22, a23 = 3, 2, 2
a31, a32, a33 = 1, 1, 2

# Dados da matriz B:
b11, b12, b13 = 1, 5, 3
b21, b22, b23 = 4, 2, 1
b31, b32, b33 = 1, 2, 2

# Primeira linha.
c11 = a11*b11 + a12*b21 + a13*b31
c12 = a11*b12 + a12*b22 + a13*b32
c13 = a11*b13 + a12*b23 + a13*b33

# Segunda linha.
c21 = a21*b11 + a22*b21 + a23*b31
c22 = a21*b12 + a22*b22 + a23*b32 
c23 = a21*b13 + a22*b23 + a23*b33

# Terceira linha.
c31 = a31*b11 + a32*b21 + a33*b31
c32 = a31*b12 + a32*b22 + a33*b32
c33 = a31*b13 + a32*b23 + a33*b33

# Cálculo dda matriz  C:
c = [[c11, c12, c13],
     [c21, c22, c23],
     [c31, c32, c33]
]

c

[[8, 16, 11], [13, 23, 15], [7, 11, 8]]

#### Exemplo

Cálcule a matriz $C = A.B$ dados por:

\begin{equation}
A =
    \begin{bmatrix}
      2 &  3  \\
      1 &  4 \\
	  2 &  1 \nonumber 
    \end{bmatrix}
    \
    \
    B =
    \begin{bmatrix}
     3  &  2  \\
	 1  &  0  \nonumber 
    \end{bmatrix}
   \end{equation}