<div style="text-align: center;">

  <!-- Logotipo -->
  <img src="LogoUesc.png" alt="UESC" style="width: 60px; display: block; margin: 0 auto 5px auto;">

  <!-- Cabeçalho -->
  <div style="font-size: 20px;"><strong>UNIVERSIDADE ESTADUAL DE SANTA CRUZ - UESC</strong></div>
  <div style="font-size: 18px;">DEPARTAMENTO DE ENGENHARIAS E COMPUTAÇÃO</div>
  <div style="font-size: 18px;">ENGENHARIA QUÍMICA</div>

  <hr style="margin: 20px 0; border: 1px solid #0074B7;">

  <!-- Título do Trabalho -->
  <div style="font-size: 22px; font-weight: bold; margin-bottom: 10px;">Modelagem, Simulação e Otimização de Processos Químicos</div>
  <div style="font-size: 20px; font-weight: bold; margin-bottom: 10px;">Simulação em Planta Química - Processo Modular</div>

  <!-- Autor e orientador -->
  <div style="font-size: 18px;">Prof. Dr. E.R.Edwards</div>

<hr style="margin: 20px 0; border: 1px solid #0074B7;">
  <!-- Data -->
<!-- <div style="font-size: 16px; margin-top: 15px;">Ilhéus - BA, Abril de 2025</div> -->
</div>

Fonte: Exemplo 7.1 do livro do Wu Hong Kong "Resolvendo problemas de Engenharia Química com Software Livre Scilab"

<div style="background-color: #e6f2ff; border-left: 6px solid #0074B7; padding: 10px; font-size: 16px;">
  <strong>Balanço material de uma bateria de coluna de destilação no estado estacionário.</strong> 
</div>

Balanço material de uma bateria de coluna de destilação no estado estacionário.


$70 \ mols/min$ de uma mistura contendo Xileno, Estireno, Tolueno e Benzeno devem ser separados por meio de uma sequência de Colunas de Destilação em que $F$, $D_1$, $B_1$, $D2$, $D_3$ e $B_3$ são vazões molares em mols/min.

<img src="img/coluna_dest_modular_1.png" alt="UESC" style="width: 650px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Bateria de Colunas de Destilação.</strong></p>

Solução:

Vamos fazer um esquema de notação para os vários componentes para facilitar o desenvolvimento de forma computacional.

<img src="img/indice_benzeno.png" alt="UESC" style="width: 350px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Indice dos componentes</strong></p>

#### Balanço Global

Agora vamos fazer um balanço global para o volume de controle compreendido pela caixa tracejada conforma ilustrado na figura abaixo.

<img src="img/coluna_dest_modular_2.png" alt="UESC" style="width: 350px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Balanço Global na Planta Química</strong></p>

Nas expressões abaixo o primeiro número do índice corresponde a coluna e o segundo número corresponde ao componente.

- Xileno:   $F_{z1} = D_2y_{21} + B_2x_{21} + D_3y_{31} + B_3x_{31}$
- Estireno: $F_{z2} = D_2y_{22} + B_2x_{22} + D_3y_{32} + B_3x_{32}$
- Tolueno:  $F_{z3} = D_2y_{23} + B_2x_{23} + D_3y_{33} + B_3x_{33}$
- Benzeno:  $F_{z4} = D_2y_{24} + B_2x_{24} + D_3y_{34} + B_3x_{34}$

Observe que a partir dos dados apresentados acima podemos  reescrever quatro equações para a forma matricial, chegando ao seguinte sistema:

\begin{equation}
\begin{bmatrix}
y_{21} & x_{x21} & y_{31} & x_{31} \\
y_{22} & x_{x22} & y_{32} & x_{32} \\
y_{23} & x_{x23} & y_{33} & x_{33} \\
y_{24} & x_{x24} & y_{34} & x_{34} 
\end{bmatrix}
.
\begin{bmatrix}
D_2 \\
B_2 \\
D_3 \\
B_3
\end{bmatrix}
=
\begin{bmatrix}
F_{z1} \\
F_{z2} \\
F_{z3} \\
F_{z4}
\end{bmatrix}
\end{equation}

A solução desse sistema de equações lineares fornece os valores de vazões $D_2$, $B_2$, $D_3$ e $B_3$.

Para calcular as vazões $D_1$ e $B_1$ e suas respectivas composições, vamos escrever os balanços de massa total e de componentes para cada coluna.

__Balanço na Coluna 1__.

A figura abaixo mostra o volume de controle na coluna 1

<img src="img/balanco_coluna_1.png" alt="UESC" style="width: 350px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Balanço material na primeira coluna.</strong></p>

Para o volume de controle na figura acima, temos:
- Massa total: $D_1 = D_2 + B_2$
- Xileno: $F_{z1} =  D_1y_{11} + B_1x_{11}$
- Estireno: $F_{z2} = D_1y_{12} + B_1x_{12}$
- Tolueno: $F_{z3} = D_1y_{13} + B_1x_{13}$
- Benzeno: $F_{z4} = D_1y_{14} + B_1x_{14}$ 

#### Balanço na coluna 2.

A figura abaixo mostra o volume de controle em torno da segunda coluna.

<img src="img/balanco_coluna_2.png" alt="UESC" style="width:350px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Balanço material na segunda coluna.</strong></p>

Para o volume de controle na Coluna 2, temos:

- Massa total: $D_1 = D_2 + B_2$
- Xileno: $D_1y_{11} = D_2y_{21} + B_2x_{21}$
- Estireno: $D_1y_{12} = D_2y_{22} + B_2x_{22}$
- Tolueno: $D_1y_{13} = D_2y_{23} + B_2x_{23}$
- Benzeno: $D_1y_{14} = D_2y_{24} + B_2x_{24}$

#### Balanço na coluna 3

A figura abaixo mostra o volume de controle em torno da segunda coluna.

<img src="img/balanco_coluna_3.png" alt="UESC" style="width: 350px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Figura: Balanço material na terceira coluna.</strong></p>

Para o volume de controle na Coluna 3, temos:

- Massa total: $B_1 = D_3 + B_3$
- Xileno: $B_1x_{11} = D_3y_{31} + B_3x_{31}$
- Estireno: $B_1x_{12} = D_3y_{32} + B_3x_{32}$
- Tolueno: $B_1x_{13} = D_3y_{33} + B_3x_{33}$
- Benzeno: $B_1x_{14} = D_3y_{34} + B_3x_{34}$

#### Programação em Python para simulação de uma coluna de destilação multiestágios.

Vamos inicialmente declarar a matriz A com os valores apresentados na tabela.

\begin{equation}
\begin{bmatrix}
y_{21} & x_{x21} & y_{31} & x_{31} \\
y_{22} & x_{x22} & y_{32} & x_{32} \\
y_{23} & x_{x23} & y_{33} & x_{33} \\
y_{24} & x_{x24} & y_{34} & x_{34} 
\end{bmatrix}
.
\begin{bmatrix}
D_2 \\
B_2 \\
D_3 \\
B_3
\end{bmatrix}
=
\begin{bmatrix}
F_{z1} \\
F_{z2} \\
F_{z3} \\
F_{z4}
\end{bmatrix}
\end{equation}

Substituindo os valores numéricos fornecidos pelo enunciado, temos:

\begin{equation}
\begin{bmatrix}
0.07 & 0.18 & 0.15 & 0.24 \\
0.04 & 0.24 & 0.10 & 0.65 \\
0.54 & 0.42 & 0.54 & 0.10 \\
0.35 & 0.16 & 0.21 & 0.01 
\end{bmatrix}
.
\begin{bmatrix}
D_2 \\
B_2 \\
D_3 \\
B_3
\end{bmatrix}
=
\begin{bmatrix}
0.15.F \\
0.25.F \\
0.40.F\\
0.20.F
\end{bmatrix}
\end{equation}

Sabendo-se que o fluxo de entrada na primeira coluna é $F = 70 \ mols/min$.

In [14]:
import numpy as np
import numpy.linalg as nl

In [15]:
# Fluxo de entrada na primeira coluna em moles/min.
F = 70.0 # mols/min.

# Balanço Global dos Componentes.
F1 = 0.15*F
F2 = 0.25*F
F3 = 0.40*F
F4 = 0.20*F

In [16]:
# Declarando a matriz A.
y21, x21, y31, x31 = 0.07, 0.18, 0.15, 0.24  # para o Xileno
y22, x22, y32, x32 = 0.04, 0.24, 0.10, 0.65  # para o Estireno
y23, x23, y33, x33 = 0.54, 0.42, 0.54, 0.10  # para o Tolueno
y24, x24, y34, x34 = 0.35, 0.16, 0.21, 0.01  # para o Benzeno


# Criado a Matriz A.
A =np.array([
    [y21, x21, y31, x31],
    [y22, x22, y32, x32],
    [y23, x23, y33, x33],
    [y24, x24, y34, x34]
])
A

array([[0.07, 0.18, 0.15, 0.24],
       [0.04, 0.24, 0.1 , 0.65],
       [0.54, 0.42, 0.54, 0.1 ],
       [0.35, 0.16, 0.21, 0.01]])

In [17]:
# Criando o vetor b
b = np.array([F1, F2, F3, F4])
b

array([10.5, 17.5, 28. , 14. ])

In [18]:
# Cálculando a variável x.
x = np.linalg.solve(A,b)
x

array([26.25, 17.5 ,  8.75, 17.5 ])

In [19]:
# Extraindo os valores numéricos da lista acima.
D2 = x[0]
B2 = x[1]
D3 = x[2]
B3 = x[3]

#### Coluna 2

In [20]:
# Balanço de massa na Coluna 2.
D1 = D2 + B2

In [21]:
# Balanço dos componentes na coluna 2.
D1y11 = D2*y21 + B2*x21 # Xileno
D1y12 = D2*y22 + B2*x22 # Estireno
D1y13 = D2*y23 + B2*x23 # Tolueno
D1y14 = D2*y24 + B2*x24 # Benzeno

In [22]:
# Cálculo da composição na Corrente de topo da coluna 1 - D1.
y11 = D1y11/D1 # Xileno
y12 = D1y12/D1 # Estireno
y13 = D1y13/D1 # Tolueno
y14 = D1y14/D1 # Benzeno

#### Coluna 3

In [23]:
# Balanço de massa na Coluna 3.
B1 = D3 + B3

In [24]:
# Balanço dos componentes na coluna 3.
B1x11 = D3*y31 + B3*x31 # Xileno
B1x12 = D3*y32 + B3*x32 # Estireno
B1x13 = D3*y33 + B3*x33 # Tolueno
B1x14 = D3*y34 + B3*x34 # Benzeno

In [25]:
# Cálculo da composição na Corrente de fundo da coluna 1 - B1.
x11 = B1x11/B1 # Xileno
x12 = B1x12/B1 # Estireno
x13 = B1x13/B1 # Tolueno
x14 = B1x14/B1 # Benzeno

#### Resultados

In [26]:
def line():
    print('-'*60)

line()
print('               RESULTADOS')
line()
print('O valor do fluxo de entrada F = ', F )
line()
print('          Vazão molar na Coluna 2   ')
line()
print('Valor da entrada de fluxo na Coluna 2, D1 = {:.2f} '.format(D1), 'mols/min')
print('Valor do fluxo de topo na Coluna 2, D2 = {:.2f} '.format(D2), 'mols/min')
print('Valor do fluxo de fundo na Coluna 2, B2 =  {:.2f}'.format(B2), 'mols/min')
line()
print('          Vazão molar na Coluna 3   ')
line()
print('Valor da entrada de fluxo na Coluna 3, B1 = {:.2f} '.format(B1), 'mols/min')
print('Valor do fluxo de topo na Coluna 3, D3 = {:.2f}'.format(D3), 'mols/min')
print('Valor do fluxo de fundo na Coluna 3, B3 {:.2f}'.format(B3), 'mols/min')
line()
print('          Composição na corrente D1')
print('A composição na corrente de topo para o Xileno é y11 =  {:.3f}'.format(y11))    
print('A composição na corrente de topo para o Estireno é y12 = {:.3f}'.format(y12))    
print('A composição na corrente de topo para o Tolueno é y13 = {:.3f}'.format(y13))      
print('A composição na corrente de topo para o Benzeno é y14 = {:.3f}'.format(y14))    
line()
print('          Composição na corrente B1')
line()
print('A composição na corrente de fundo para o Xileno é x11 =  {:.3f}'.format(x11))    
print('A composição na corrente de fundo para o Estireno é x12 = {:.3f}'.format(x12))    
print('A composição na corrente de fundo para o Tolueno é x13 = {:.3f}'.format(x13))      
print('A composição na corrente de fundo para o Benzeno é x14 = {:.3f}'.format(x14))    
line()
  

------------------------------------------------------------
               RESULTADOS
------------------------------------------------------------
O valor do fluxo de entrada F =  70.0
------------------------------------------------------------
          Vazão molar na Coluna 2   
------------------------------------------------------------
Valor da entrada de fluxo na Coluna 2, D1 = 43.75  mols/min
Valor do fluxo de topo na Coluna 2, D2 = 26.25  mols/min
Valor do fluxo de fundo na Coluna 2, B2 =  17.50 mols/min
------------------------------------------------------------
          Vazão molar na Coluna 3   
------------------------------------------------------------
Valor da entrada de fluxo na Coluna 3, B1 = 26.25  mols/min
Valor do fluxo de topo na Coluna 3, D3 = 8.75 mols/min
Valor do fluxo de fundo na Coluna 3, B3 17.50 mols/min
------------------------------------------------------------
          Composição na corrente D1
A composição na corrente de topo para o Xileno é y11 =

<div style="text-align: center; font-size: 12px; color: gray; margin-top: 40px;">
  Este notebook foi desenvolvido no âmbito do Grupo de Pesquisas em Modelagem Computacional da UESC.<br>
  Todos os direitos reservados © 2025
</div>