<div style="text-align: center;">

  <!-- Logotipo -->
  <img src="img/LogoUesc.png" alt="UESC" style="width: 60px; display: block; margin: 0 auto 5px auto;">

  <!-- Cabeçalho -->
  <div style="font-size: 20px;"><strong>UNIVERSIDADE ESTADUAL DE SANTA CRUZ - UESC</strong></div>
  <div style="font-size: 18px;">DEPARTAMENTO DE ENGENHARIAS E COMPUTAÇÃO</div>
  <div style="font-size: 18px;">ENGENHARIA QUÍMICA</div>

  <hr style="margin: 20px 0; border: 1px solid #0074B7;">

  <!-- Título do Trabalho -->
  <div style="font-size: 22px; font-weight: bold; margin-bottom: 10px;">Modelagem, Simulação e Otimização de Processos Químicos</div>
  <div style="font-size: 20px; font-weight: bold; margin-bottom: 10px;">Cálculos - Processo de Saparação de Componentes do Petróleo</div>

  <!-- Autor e orientador -->
  <div style="font-size: 18px;">Prof. Dr. E.R.Edwards</div>

<hr style="margin: 20px 0; border: 1px solid #0074B7;">
  <!-- Data -->
<!-- <div style="font-size: 16px; margin-top: 15px;">Ilhéus - BA, Abril de 2025</div> -->
</div>

__QUESTÃO 1__:

Suponhamos que temos quatro componentes principais no petróleo bruto: **gasolina (G)**, **diesel (D)**, <br> **querosene (Q)** e **resíduos (R)**. Queremos separar esses componentes usando um processo de destilação. <br> As frações molares iniciais de cada componente no **petróleo bruto** são dadas por:

- Fração molar inicial de **gasolina**: 0.2
- Fração molar inicial de **diesel**: 0.3
- Fração molar inicial de **querosene**: 0.4
- Fração molar inicial de **resíduos**: 0.1

O processo de destilação produz quatro correntes de produtos com as seguintes frações molares:

- Corrente de gasolina (G): **Fração molar de gasolina** = 0.8
- Corrente de diesel (D): **Fração molar de diesel** = 0.5
- Corrente de querosene (Q): **Fração molar de querosene** = 0.2
- Corrente de resíduos (R) : **Fração molar de resíduos** = 0.1

<img src="img/Q1_CET1012_corrente.png" alt="UESC" style="width: 650px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;"><strong>Tabela: Composição dos elementos de cada corrente.</strong></p>

__Obs__: No processo de separação, apenas aquele componente específico será separado naquela determinada corrente.<br>
Dessa forma, na corrente 1 só será separado o componente Gasolina, na corrente 2 só será separado o componente <br>
Diesel, assim por diante.

A matriz $A$ representa as frações molares dos componentes nas correntes de produtos.

Portanto, temos:

\begin{equation}
 A = 
 \begin{bmatrix}
 0.8 & 0 & 0 & 0 \\
 0 & 0.5 & 0 & 0 \\
 0 & 0 & 0.2 & 0 \\
 0 & 0 & 0 & 0.1 
 \end{bmatrix} 
\end{equation}

E o vetor $b$ representa as frações molares iniciais no Petróleo bruto.

\begin{equation}
 b = 
 \begin{bmatrix} 
 0.2 \\
 0.3 \\
 0.4 \\
 0.1 
 \end{bmatrix} 
\end{equation}

__Resolução usando biblioteca Numpy__

In [92]:
import numpy as np

In [93]:
# Declarando a matriz:
a11, a12, a13, a14 = 0.8, 0.0, 0.0, 0.0
a21, a22, a23, a24 = 0.0, 0.5, 0.0, 0.0
a31, a32, a33, a34 = 0.0, 0.0, 0.2, 0.0
a41, a42, a43, a44 = 0.0, 0.0, 0.0, 0.1


In [94]:
# Definindo a matriz A e o vetor b
A = np.array([
    [a11, a12, a13, a14],
    [a21, a22, a23, a24],
    [a31, a32, a33, a34],
    [a41, a42, a43, a44]
])
A

array([[0.8, 0. , 0. , 0. ],
       [0. , 0.5, 0. , 0. ],
       [0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0.1]])

In [95]:
# Declarando a matriz b.
b11, b12, b13, b14 = 0.2, 0.3, 0.4, 0.1

In [96]:
# Calculando a matriz b.
b = np.array([b11, b12, b13, b14])
b

array([0.2, 0.3, 0.4, 0.1])

In [97]:
# Resolvendo o Sistema Linear.
x = np.linalg.solve(A, b)

x_gasolina  = x[0]   # Fração molar da Gasolina (G)
x_diesel    = x[1]   # Fração molar do Diesel (D)
x_querosene = x[2]   # Fração molar do Querosene (Q)
x_residuos  = x[3]   # Fração molar dos Resíduos (R)

In [132]:
# Imprimindo os resultados

def line():
    print('-'*45)
    
line()    
print('\t Frações molares dos componentes: ')
line()
print('Frações molares da Gasolina (G) = {:.2f}'.format(x_gasolina))
print('Frações molares do Diesel (D) = {:.2f}'.format(x_diesel))
print('Frações molares do Querosene (Q) = {:.2f}'.format(x_querosene))
print('Frações molares dos Resíduos(R) = {:.2f}'.format(x_residuos))
line()

---------------------------------------------
	 Frações molares dos componentes: 
---------------------------------------------
Frações molares da Gasolina (G) = 0.25
Frações molares do Diesel (D) = 0.60
Frações molares do Querosene (Q) = 2.00
Frações molares dos Resíduos(R) = 1.00
---------------------------------------------


__Conferindo os resultados__

In [99]:
z1 = a11*x_gasolina
z2 = a22*x_diesel
z3 = a33*x_querosene
z4 = a44*x_residuos

In [100]:
print(f'O valor de b1={b11} e o valor de z1={z1}')
print(f'O valor de b2={b12} e o valor de z2={z2}')
print(f'O valor de b3={b13} e o valor de z3={z3}')
print(f'O valor de b3={b14} e o valor de z3={z4}')

O valor de b1=0.2 e o valor de z1=0.2
O valor de b2=0.3 e o valor de z2=0.3
O valor de b3=0.4 e o valor de z3=0.4
O valor de b3=0.1 e o valor de z3=0.1


__QUESTÃO 3__:

A figura mostra uma coluna de separação da mistura dos componentes **Propileno** e **Propano**. A vazão de entrada dos componentes é de $272.2\  Kmol/h $ de forma que $163.3 \ kmol/h$ corresponde a vazão de entrada para o  Propileno e $108.9 \ Kmol/h$ para o  Propano. Sabendo-se que na corrente de topo as vazões de saída correspondem a $157.6 \ Kmol/h$ para o Propileno e $1.6 \ Kmol/h$ para o Propano e na corrente de fundo as vazões de saída são $5.7 \ Kmol/h$ para o Propileno e $107.3 \ Kmol/h$ para o Propano. Pede-se: Aplique a **Regra de Cramer**
e determine de **forma algébrica** as frações $x$ e $y$ de cada componente.   Resolva utilizando **métodos algébricos** e programação em Python para determinação das frações de cada componente. Declare cada variável de forma que seu modelo possa ser utilizado com outros valores. Confira os resultados utilizando uma biblioteca de cálculo em Python. [2.5 pontos]


<img src="img/separador_seader.png" alt="UESC" style="width: 450px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;">Fonte<strong>: Seader, et. all " Separation Process Principles - Chemical ad Biochemical Operations" 3a Ed.</strong></p>

__Vamos colocar os dados em forma matricial__.

Seja $x$ a fração do Propileno e $y$ a fração do Propano, então temos:

$$ 157.6x +   5.7y = 163.3 $$
$$   1.6x + 107.3y = 108.9 $$

Então vamos chamar de:

$a_1$... fração de Propileno na corrente de topo <br>
$b_1$... fração do Propileno na corrente de fundo <br>

$a_2$...fração do Propano na corrente de topo <br>
$b_2$... fração do Propano na corrente de fundo <br>

$d_1$... vazão de Propileno na entrada do processo <br>
$d_2$... vazão de Propano na entrada do processo <br>

Então teremos:

$$ a_1x + b_1y = d_1 $$
$$ a_2x + b_2y = d_2 $$

Vamos resolver aplicando a **Regra de Cramer** para determinar as incógnitas.

__Aplicando Método Álgébrico__


$$a_{11}x +   a_{12}y = b_{11} $$
$$a_{21}x + a_{22}y = b_{21}$$

Em valores numéricos, temos:

$$ 157.6x +   5.7y = 163.3 $$
$$   1.6x + 107.3y = 108.9 $$

In [101]:
# Declarando as variáveis, temos:
a11, a12 = 157.6, 5.7
a21, a22 = 1.6, 107.3

In [102]:
# Declarando os valores de entrada no processo.
b11, b21 = 163.3, 108.9

Então teremos:

$$ a_{11}x +   a_{12}y = b_{11} $$
$$ a_{21}x + a_{22}y = b_{21}$$

Vamos resolver aplicando a **Regra de Cramer** para determinar as incógnitas.

In [103]:
# Declarando as variáveis, temos:
a11, a12 = 157.6, 5.7
a21, a22 = 1.6, 107.3

Cálculo do Determinante:

$$ a_{11} + a_{12} $$
$$ a_{21} + a_{22} $$

In [104]:
# Cálculo do Determinante.
D = a11*a22 - a12*a21
D

16901.36

Cálculo do Determinante  $Dx$.

Temos que substituir os termos da coluna $d$ no lugar dos termos da coluna $x$. 

$$ b_{11} + a_{12} $$
$$ b_{21} + a_{22} $$

In [105]:
# Cálculo de Dx
Dx = b11*a22 - a12*b21
Dx

16901.36

Agora vamos cálculo o Determinante $Dy$.

Temos que substituir os termos da coluna $d$ no lugar dos termos da coluna $y$. 

$$a_{11} + b_{11} $$
$$a_{21} + b_{21} $$

In [106]:
Dy = a11*b21 - b11*a21
Dy

16901.36

In [107]:
# Cálculo das incógnitas.
x = Dx/D
y = Dy/D

def line():
    print('-'*30)

line()
print('\t Resultados')
line()
print('O resultado de x = ', x)
print('O resultado de y = ',y)
line()

------------------------------
	 Resultados
------------------------------
O resultado de x =  1.0
O resultado de y =  1.0
------------------------------


Para conferir os resultados, vamos voltar nos dados iniciais.

$$ a_{11}x + a_{12}y = b_{11} $$
$$ a_{21}x + a_{22}y = b_{21} $$

Os valores numéricos de $a_{ij}$ são dados abaixo:

$$ 157.6x + 5.7y = 163.3 $$
$$ 1.6x + 107.3y = 108.9 $$

In [108]:
# Conferindo os resultados.
z1 = a11*x + a12*y
z2 = a21*x + a22*y

def line():
    print('-'*40)

line()
print(' \t Conferindo os resultados ')
line()
print('O valor de d1 = 163.3 e z1 = {:.2f}'.format(z1))
print('O valor de d2 = 108.9 e z2 = {:.2f}'.format(z2))
line()

----------------------------------------
 	 Conferindo os resultados 
----------------------------------------
O valor de d1 = 163.3 e z1 = 163.30
O valor de d2 = 108.9 e z2 = 108.90
----------------------------------------


Agora, vamos usar a biblioteca NumPy para resolver o mesmo exercício.

In [109]:
import numpy as np

Vamos montar a matriz visualizando os dados iniciais.

$$ a_{11}x + a_{12}y = b_{11} $$
$$ a_{21}x + a_{22}y = b_{21} $$

Em valores numéricos, temos:

$$ 157.6x + 5.7y = 163.3 $$
$$ 1.6x + 107.3y = 108.9 $$

In [110]:
# Declarando a Matriz A.
A = np.array([
    [a11, a12],
    [a21, a22]
])
print(A)

[[157.6   5.7]
 [  1.6 107.3]]


In [111]:
# Cálculo da matriz inversa.
A_inv = np.linalg.inv(A)
A_inv

array([[ 6.34860153e-03, -3.37250967e-04],
       [-9.46669380e-05,  9.32469340e-03]])

In [112]:
# Declarano a matriz b.
b = np.array([b11,b21])
print(b)

[163.3 108.9]


In [113]:
# Cálculo das incógnitas.
x = A_inv.dot(b)
x11 = x[0] # x11 apenas para diferencial e x1 do cálculo anterior
x22 = x[1] # x22 apenas para diferencial e x2 do cálculo anterior

In [114]:
# Imprimindo os resultados

def line():
    print('-'*30)

line()
print('\t  Resultados')
line()
print('O resultado de x = {:.1f}'.format(x11))
print('O resultado de y = ', x22)
line()

------------------------------
	  Resultados
------------------------------
O resultado de x = 1.0
O resultado de y =  1.0
------------------------------


Ou poderiamos ter resolvido da seguinte forma.

In [115]:
k = np.linalg.solve(A, b)
print(k)

[1. 1.]


Observe que linalg.solve faz a inversa da matriz $A$ e inverte a matriz $\vec{b}$ para ser multiplicado pela matriz inversa $A^{-1}$. <br>
Faz tudo isso em uma linha de código.

__QUESTÃO 4__:


__Tema do Exercício: Destilação de Mistura Binária__

Suponhamos que temos uma mistura binária de dois componentes $A$ e $B$ e queremos separar<br>  usando um processo de Destilação. As frações molares iniciais de cada componente na mistura são dadas por:

* Fração molar inicial de **A**: $0.6$
* Fração molar inicial de **B**: $0.4$

Durante a destilação, obtemos duas correntes de produtos:

<br>1 - Corrente de topo (**overhead**): Fração molar de A na corrente de topo = $0.8$
<br>2 - Corrente de fundo (**bottom**): Fração molar de A na corrente de fundo = $0.2$

<br>A matriz $A$ representa as frações molares dos componentes nas correntes de produtos e o 
<br>vetor $b$ representa as frações molares iniciais na mistura. Monte um Sistema de Equações
<br>Linear para o cálculo das frações de cada componente. Para resolução desse sistema Linear, 
<br>$Ax=b$, use o método algébrico e confira os resultados usando a biblioteca *Numerical Python*.

<img src="img/Q4_CET1012_sep_comp.png" alt="UESC" style="width: 650px; display: block; margin: 0 auto 5px auto;">
<p style="text-align: center;">Figura<strong>: Coluna de separação.</strong></p>

**Obs**: Os valores obtidos para as frações molares dos componentes após a destilação serão impressos na saída.
<br>Lembre-se de adaptar os valores e as matrizes conforme necessário para diferentes cenários de separação em Engenharia Química.

Calculos:

Declarando a matriz A:
\begin{equation}
 A = 
 \begin{bmatrix}
 0.8 & 0  \\
 0 & 0.2  
 \end{bmatrix} 
\end{equation}

Declarando a matriz b:

\begin{equation}
 b = 
 \begin{bmatrix}
 0.6   \\
 0.4
 \end{bmatrix} 
\end{equation}


__Cálculo pelo Método Álgebrico__.

In [116]:
# Declarando a Matriz A.
a11, a12 = 0.8, 0
a21, a22 = 0, 0.2

In [117]:
# Cálculo de A^-1

# Cálculo da inversa da Matriz A.

A_inv = (1/(a11*a22 - a12*a21))*np.array([[a22, -a12],
                                         [-a21, a11]])
                                         
A_inv

array([[1.25, 0.  ],
       [0.  , 5.  ]])

In [118]:
# Declarando a matriz b:
b11 = 0.6
b12 = 0.4

In [119]:
# Cálculo algébrico 
x_tp = 1.25*b11 
x_fd = 5.0*b12

In [120]:
# Resultados:
def line():
    print('-'*70)

line()
print('\t Frações molares dos compontentes após a destilação:')
line()
print('Frações molares de A na corrente de topo = {:.2f}'.format(x_tp))
print('Fraçõe molares de B na corrente de fundo = {:.2f}'.format(x_fd))
line()

----------------------------------------------------------------------
	 Frações molares dos compontentes após a destilação:
----------------------------------------------------------------------
Frações molares de A na corrente de topo = 0.75
Fraçõe molares de B na corrente de fundo = 2.00
----------------------------------------------------------------------


__Conferindo os resultados__.

Usando a biblioteca NumPy.

In [121]:
z1  = 1.25*b11
z2 = 5.0 * b12

In [122]:
# Resultados:
def line():
    print('-'*40)

line()
print(' \t Frações molares inicial:')
line()
print('Frações molares iniciais de A = {:.4f}'.format(z1))
print('Fraçõe molares iniciais de B = {:.4f}'.format(z2))
line()

----------------------------------------
 	 Frações molares inicial:
----------------------------------------
Frações molares iniciais de A = 0.7500
Fraçõe molares iniciais de B = 2.0000
----------------------------------------


In [123]:
import numpy as np

In [124]:
A = np.array([
    [0.8, 0],
    [0, 0.2]
])
A

array([[0.8, 0. ],
       [0. , 0.2]])

In [125]:
b = np.array([0.6, 0.4])
b

array([0.6, 0.4])

In [126]:
# Resolvendo o Sistema Linear.
x = np.linalg.solve(A,b)
x_topo = x[0]
x_fundo = x[1]

In [127]:
# Resultados:
def line():
    print('-'*65)

line()
print(' \t Frações molares dos compontentes após a destilação:')
line()
print('Frações molares de A na corrente de topo = {:.4f}'.format(x_topo))
print('Fraçõe molares de A na corrente de fundo = {:.4f}'.format(x_fundo))
line()

-----------------------------------------------------------------
 	 Frações molares dos compontentes após a destilação:
-----------------------------------------------------------------
Frações molares de A na corrente de topo = 0.7500
Fraçõe molares de A na corrente de fundo = 2.0000
-----------------------------------------------------------------


__Conferindo os resultados__.

In [128]:
z_1  = 1.25*b11
z_2 = 5.0*b12

In [129]:
# Resultados:
def line():
    print('-'*40)

line()
print(' \t Frações molares inicial:')
line()
print('Frações molares iniciais de A = {:.2f}'.format(z_1))
print('Fraçõe molares iniciais de B = {:.2f}'.format(z_2))
line()

----------------------------------------
 	 Frações molares inicial:
----------------------------------------
Frações molares iniciais de A = 0.75
Fraçõe molares iniciais de B = 2.00
----------------------------------------
